### ISSUE TITLE
Renamed minis reset to default name after leaving board

### ISSUE THREAD

**Issue by MallowOni** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#811] opened 2021-04-18 03:34 UTC
**Describe the bug**
Minis renamed after the April 16th Bug Fix Patch 01 cannot be permanently renamed. Pictured below is one of my gallery boards. Each of those slimes was renamed to the name of the slab plus its creator. As soon as I leave the board or close Talespire their names reset to default. Relaunching does not fix it. Renaming them again does not help either. Minis renamed prior to the patch are unaffected.

**Screenshots/Videos/Twitch Clips**
![image](https://user-images.githubusercontent.com/63642460/115133290-b85a4300-9fcc-11eb-9268-da7fb46ece7d.png)

**Comment by KatLadyKing** [comment] 2021-04-18 16:54
I as well deal with this issue when attempting to rename "Human Solider" miniatures and "Catfolk Warrior". Im sure there are more but these are the only issues I have had thus far. Love the program guys! Keep it up! Amazing.

**Comment by MallowOni** [comment] 2021-04-21 11:34
After further testing the issue is somewhat inconsistent. In the screenshot below I placed the top right slime from my hotbar & named it "What's my name", and placed the top left slime & named it "From the library" because I pulled the mini from the library instead, trying to see if the source the mini was spawned from would make a difference. When I logged out and back in they both kept their new names. While still logged in after checking on the first pair of slimes I then spawned "Library nerd" from the library, followed by "Nemo" from the hotbar, and again exited & restarted Talespire. This time "From the library" had reverted to "Slime" as you see here so I tried renaming "Nemo" to "Nemo 2" and then closed & restarted Talespire. "Slime" remained "Slime" and "Nemo 2" reverted to "Nemo".

![image](https://user-images.githubusercontent.com/63642460/115546880-2cb21200-a26b-11eb-86cb-879b2dc5611e.png)

**Comment by cbaggers** [comment] 2021-04-21 16:26
@MallowOni @KatLadyKing thanks for all the info folks. It does seem like there are cases where syncing is inconsistent I'll have a poke and see if I can replicate this

**Comment by cbaggers** [comment] 2021-04-21 16:48
Yup, I can confirm this. The issue is that renaming the mini is not marking the data as needing syncing to the server and so, unless there is another change (such as moving the creature) the name change is lost.
I'll fix this now

**Comment by cbaggers** [comment] 2021-04-21 16:53
The fix for this will be in the next patch. Thanks again!

**Comment by MallowOni** [comment] 2021-04-21 17:12
> 
> 
> Yup, I can confirm this. The issue is that renaming the mini is not marking the data as needing syncing to the server and so, unless there is another change (such as moving the creature) the name change is lost.

That gives me a workaround to try in the meantime. Thanks.

**Comment by LuPro** [comment] 2021-04-22 14:33
Should be fixed now, could you confirm?

**Comment by KatLadyKing** [comment] 2021-04-27 13:21
I can, in all instances. You guys rock.

**Closed** 2021-04-27 19:00 UTC
Labels: bug, waiting on user confirmation of fix
