### ISSUE TITLE
Swapped Main Mouse Buttons doesn't allow for placement of tiles.

### ISSUE THREAD

**Issue by OrphRedHair** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#388] opened 2020-04-16 15:32 UTC
**Describe the Bug:**
My mouse buttons are swapped into a left-handed orientation, and the game doesn't seem to like it. I will go into build mode, select an item to place, and no matter which button I click the item vanishes and doesn't place.

The issue gets resolved when I switch my main mouse buttons back to a right-handed orientation, but this issue seems inconvenient for left handed folk.

Here's a GIF of the process. The first time is me using my left mouse button, and then the second with my right mouse button.
https://gyazo.com/d7efe356a711e50d2077f91413069924

Interestingly, I am able to place creatures as intended:
https://gyazo.com/2db05913a73a608af6b4f77a83755d8d

**Comment by LuPro** [comment] 2020-04-16 18:01
Duplicate of #136, but nice extra information

**Closed by LuPro** 2020-04-16 18:01 UTC
