### ISSUE TITLE
Clicking and dragging mouse while laying down 'Cobblestone Floor - Small' crashes the program (Windows 7)

### ISSUE THREAD

**Issue by MikeMyler2** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#12] opened 2020-04-10 19:49 UTC
**Describe the bug**
Didn't think it was _supposed_ to do anything, but when I accidentally clicked and dragged while the 'Cobblestone Floor - Small' asset was selected it crashed the program and corrupted the project file.

**To Reproduce**
1. Open a new project
2. Lay down some 'Cobblestone Floor - Large' assets
3. Select 'Cobblestone Floor - Small' asset
4. Lay one asset down
5. Click and drag with mouse
6. Talespire crashes

**Screenshots/Videos/Twitch Clips**
Unable to obtain.

**Comment by LuPro** [comment] 2020-04-11 11:23
Unable to reproduce (Windows 10), together with this and #7, I'm beginning to think TaleSpire isn't very stable on Windows 7 - might need some more data to figure out what the common denominator is in what causes these crashes

**Comment by LuPro** [comment] 2020-05-26 15:29
The latest update likely contains a fix for this - could you please check if this is the case for you?

**Comment by MikeMyler2** [comment] 2020-06-02 04:32
Works great :)
![image](https://user-images.githubusercontent.com/63473946/83480102-7eda2100-a468-11ea-99ff-251f9d4b58e3.png)

**Closed** 2020-06-02 20:34 UTC
Labels: bug, corrupts save
