### ISSUE TITLE
Wooden fence misalignement.

### ISSUE THREAD

**Issue by softwetsticky** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#391] opened 2020-04-16 17:19 UTC
Wooden fences currently don't connect properly because their models are misaligned. My friend knows a lot more about 3d modeling says that the origin gizmo not be centred is probably the issue. I've included a screenshot so you can see what I mean.
![image](https://user-images.githubusercontent.com/36275820/79486426-966f5e80-800e-11ea-878e-97642747a761.png)

**Comment by LuPro** [comment] 2020-04-16 18:05
Duplicate of #48 / #238 (and loosely some others about that topic)

**Closed by LuPro** 2020-04-16 18:05 UTC
