### ISSUE TITLE
Unknown creatures in turn order

### ISSUE THREAD

**Issue by Voidable** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#83] opened 2020-04-10 23:55 UTC
**Describe the bug**
It appears that any tokens added to the turn order from another board will appear as white squares with "unknown" as the names. They cannot be removed from the turn order without switching back to the board they were from.

**To Reproduce**
1. Create tokens.
2. Switch to Turnbased mode.
3. Add the tokens to the turn order.
4. Switch to a different board.

**Screenshots/Videos/Twitch Clips**
This image is from the second board, which only has the Blacksmith token on it.
![image](https://user-images.githubusercontent.com/11160887/79029912-87973080-7b64-11ea-9142-cb11298f56ae.png)
This image is showing the edit turn order view, which shows the proper icons and names of the other tokens.
![image](https://user-images.githubusercontent.com/11160887/79029948-bad9bf80-7b64-11ea-872d-b50cfe03af66.png)

**Additional context**
I've tested this with different types of tokens, and with making one of the tokens a unique character, with no apparent difference.
If you've deleted the board the tokens are from, the only way I've found to remove the tokens from the turn order is to relaunch TaleSpire.

**Comment by gabefoster** [comment] 2020-04-11 01:39
I was able to reproduce this issue without switching or deleting boards, just by deleting a creature from the initiative order, and then adding another (unrelated) creature to the initiative order.

**Comment by LuPro** [comment] 2020-04-11 21:56
Seems similar to #56 but has some other info

**Comment by LuPro** [comment] 2020-04-12 13:08
> 
> 
> I was able to reproduce this issue without switching or deleting boards, just by deleting a creature from the initiative order, and then adding another (unrelated) creature to the initiative order.

I can confirm being able to reproduce this

**Comment by hopstar117** [comment] 2020-04-15 11:52
Was able to reproduce while running a combat test, killed npc's would initially disappear from tracking but would randomly re-appear while continuing combat

**Comment by cbaggers** [comment] 2020-04-17 00:49
Excellent work folks. I've been able to to trivially recreate the original version of the bug, which occurs on board change. I'll fix this first and then we'll get to the others

**Comment by cbaggers** [comment] 2020-04-17 00:51
Oh excellent I've managed to get @gabefoster's version too

**Comment by cbaggers** [comment] 2020-04-17 01:06
I have a potential fix for @Voidable's version of this issue. It will be in tomorrow's patch

**Comment by cbaggers** [comment] 2020-04-17 01:13
I have a potential fix for @gabefoster's version of this issue too. It will be in tomorrow's patch

**Comment by cbaggers** [comment] 2020-04-17 01:16
@hopstar117 I havent been able to recreate your version now that the other two fixes are in. Once the patch is out it would be ace if you could test to see if it worked for you too

**Comment by LuPro** [comment] 2020-04-28 01:10
Since I haven't seen any further reports of this, I think this can be considered to be fixed. If the issue still persists for someone here, please comment so this issue can be reopened

**Closed by LuPro** 2020-04-28 01:10 UTC
Labels: bug, reproducible, waiting on user confirmation of fix
