### ISSUE TITLE
Black Artifacts?

### ISSUE THREAD

**Issue by Kittyfloss** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#991] opened 2021-06-24 00:44 UTC
I was working on a town, and went to look at other parts of it to find two black rectangular objects that are un-selectable and permanent. When I try to click on them, I click on whatever was behind it. When I drag items to them, the items act normally. These black objects don't have collision, they are just black voids.

I restarted the game, and they were still there.

Here are the pictures. This is my first time using GitHub, so I'm not sure if these will work...

![black obj 1 2 0](https://user-images.githubusercontent.com/86387863/123184254-29dcc480-d448-11eb-854b-9107ddbd5798.PNG)

![black obj 2](https://user-images.githubusercontent.com/86387863/123184184-06197e80-d448-11eb-8a78-7087731c5ac3.PNG)

I'm very curious as to what these are. They didn't crash my game. Honestly these would be a really good "fog of war" item.

**Comment by LuPro** [comment] 2021-06-24 20:19
This is the experimental fog of war - did you by any chance accidentally set a keybind to it in the settings?

**Comment by Trisscar05** [comment] 2021-07-06 03:14
For my group it was that sections of floor and wall sometimes don't load, leaving a black area till you mess with the green cutbox slider.

**Comment by ohQQ** [comment] 2021-07-14 14:26
most definitely fog of war, create a selection box around them and hit the button you bound in the second tab of options menu for destroying fog of war.

**Comment by baggers-br** [comment] 2021-08-17 23:11
@LuPro and @ohQQ are correct here. Gonna close this as it's not a bug, but do let us know if you have any trouble finding the settings to remove the fog :)

**Closed by baggers-br** 2021-08-17 23:11 UTC
Labels: question
