### ISSUE TITLE
Figurine permanently tilts while moving during animation

### ISSUE THREAD

**Issue by Lemuura** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#917] opened 2021-05-10 16:15 UTC
While using the Magic Missile attack and then moving the figurine who did the attack before the animation finishes permanently tilts the figure.

1. Use the Magic Missile attack on another character (possibly have to do it multiple times before the first animation finishes)
2. Move character violently back and forth before the animation finishes
3. When the animation ends it permanently keeps the character tilt from moving it

(It does reset if you teleport the character, but only on the client side. If the GM teleports you the tilt disappears for everyone else but not for you, and when you move again the tilt shows up again for everyone else)

![TS_1620663179](https://user-images.githubusercontent.com/16639245/117690762-7bdcca00-b1bb-11eb-9f0c-f5beef383683.png)

![TS_1620663542](https://user-images.githubusercontent.com/16639245/117691492-3e2c7100-b1bc-11eb-8feb-d7b67bdffcef.png)

**Comment by LuPro** [comment] 2021-05-11 14:39
Duplicate of #791

**Closed by LuPro** 2021-05-11 14:39 UTC
