### ISSUE TITLE
Flames and crystals improperly rendered once placed

### ISSUE THREAD

**Issue by pyrestriker** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#659] opened 2021-04-01 08:08 UTC
**Describe the bug**
Crystals and flames do not apply light to themselves and instead only what is around them As a result you get some dark fire and the crystals just look super strange. This applies to all crystals, and anything that has the flame texture like candles, campfires, etc.

**To Reproduce**
Place a crystal or a prop with a flame. While in hand, it appears normal. Once placed, super dark. This is also applying to upgraded board assets.

**Screenshots/Videos/Twitch Clips**
Crystals
https://youtu.be/WOr3BfqUtL4
Flames
https://youtu.be/QyOLHy8Pp-8

**Comment by zorum24** [comment] 2021-04-01 10:40
Having similar issues but crystals will have their proper coloring but occasionally be broken looking.

(On an RTX 2070 Super)

**Comment by LuPro** [comment] 2021-04-01 10:47
Works fine for me (GTX 1080), maybe RTX card related?

**Comment by Ja07sj** [comment] 2021-04-01 14:01
I'm gettin the same behaviour on a desktop with a 2080 TI and on a laptop with Intel XE graphics:

https://imgur.com/a/ri3AjQF (laptop)
https://imgur.com/D8w8gHy (desktop - preview vs placed)

Same thing seems to be true for every light source:
https://imgur.com/a/C8yk3HE

Seems to be related to this issue as well:
https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/issues/648

**Comment by PanoramicPanda** [comment] 2021-04-01 17:02
Just to add: Works fine on an RTX 2060S, so unsure on relation to RTX.

**Comment by PanoramicPanda** [comment] 2021-04-01 18:06
Alright, think I found a reliable way to reproduce if anyone else wants to give it a shot:

1. Create new campaign
2. Paste [this slab](https://pastebin.com/hXpCPmGU) onto board
3. Lights should start breaking

[Player.log](https://pastebin.com/2WiKYgPR)

**Comment by LuPro** [comment] 2021-04-04 22:50
This should be fixed now, I tried it and it works on my end, can some others confirm so I can close the issue?

**Comment by PanoramicPanda** [comment] 2021-04-05 00:02
![image](https://user-images.githubusercontent.com/1569246/113525045-ae722200-9580-11eb-9e84-060f2884a8ce.png)
Fixed

**Closed** 2021-04-05 12:13 UTC
Labels: bug, waiting on user confirmation of fix
