### ISSUE TITLE
The single standing lantern

### ISSUE THREAD

**Issue by persgorilla** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#789] opened 2021-04-16 23:28 UTC
**Describe the bug**
I can't get the single standing lantern to work.

**To Reproduce**
1. Put single standing lantern on board.

![image](https://user-images.githubusercontent.com/82684728/115093941-1c034400-9ed9-11eb-91b2-e66a710b98e2.png)

**Comment by LuPro** [comment] 2021-04-17 01:08
Duplicate of #648

**Closed by LuPro** 2021-04-17 01:08 UTC
