### ISSUE TITLE
Copy of some elements causes crash of Talespire

### ISSUE THREAD

**Issue by derekstodghill** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#964] opened 2021-05-31 19:11 UTC
**Describe the bug**
Talespire is crashing when trying to copy some elements of my board. If I try to copy the whole board as a slab, it will crash consistently. Copying only portions of the board will sometimes work. I've not been able to narrow down which elements cause the crash however.

**To Reproduce**
1. Create a new campaign and add this board to it. talespire://published-board/SGF1bnRlZCBIb3VzZSBvZiBTYWx0bWFyc2g=/23488ed84d943d09a5934dafaf297d45
2. Open the select volume box around the area and press Ctrl + C to try and copy it.
3. Repeat if necessary
4. TaleSpire crashed

**Screenshots/Videos/Twitch Clips**
![TalespireCrash](https://user-images.githubusercontent.com/68213422/120232805-f1b3de80-c219-11eb-83fe-33c4ef66fb98.png)

**Additional context**
Crash Logs.
[Player.log](https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/files/6571928/Player.log)
[error.log](https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/files/6571927/error.log)

**Comment by cbaggers** [comment] 2021-06-01 11:05
Wow, thanks so much for this report. I'll test this now

**Comment by cbaggers** [comment] 2021-06-01 11:27
I can reproduce the issue. The problem is in the rendering of the copied slab.
It can be reproduced by trying to paste a slab with more than 13000 of a single kind of tile or prop.

New repro:
- choose a single 1x1 tile
- drag out 50x50 slab
- copy all those tiles
- paste six times on top of the original tiles
- select all tiles
- copy
- note crash (or errors in editor)

**Comment by cbaggers** [comment] 2021-06-01 14:07
The fix for this is going well. I can now copy the board without errors. However the solution could perform fewer allocations, so I'm going to look into optimizing that now

**Comment by cbaggers** [comment] 2021-06-01 16:26
I'm now satisfied with the fix. Reduce some code duplication and removed the extra de/allocations.
The fix for this bug should be in the next patch

**Comment by baggers-br** [comment] 2021-12-05 21:27
This fix has been stable in the wild for a while and so I'm going to close this ticket.
Thanks again for all the help bringing this to light!

**Closed by baggers-br** 2021-12-05 21:27 UTC
Labels: bug, potentially fixed in next patch
