### ISSUE TITLE
On open, cannot use keyboard to navigate until mouse is used to navigate first.

### ISSUE THREAD

**Issue by ScottinNH** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#458] opened 2020-04-21 12:53 UTC
**Describe the bug**
Here tell us what you thought was meant to happen and then how TaleSpire vomited on itself
When a map is opened should be able to navigate using the map using the keyboard.  Instead on opening a map the keyboard cannot be used to navigate until mouse is used to navigate first.

**To Reproduce**
1. Open map.
2. Try using keyboard to navigate map.
3. Unable to use keyboard until after the mouse is used to navigate map.

Reproducible.

**Comment by SqueeziestBee** [comment] 2020-04-21 13:02
Happens to me too

**Comment by LuPro** [comment] 2020-04-21 13:37
Duplicate of #130

**Closed by LuPro** 2020-04-21 13:37 UTC
Labels: reproducible
