### ISSUE TITLE
Deleted the level I was on.

### ISSUE THREAD

**Issue by Chezeret** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#120] opened 2020-04-11 03:27 UTC
**Describe the bug**
Here tell us what you thought was meant to happen and then how TaleSpire vomited on itself:
I created a new campaign, started laying down assets, tried to delete the assets, was unable to figure that out, tried to delete the level to start fresh. I thought I would still be on a menu and given the option to create a new level. Instead it took away all the campaign functions. I could still quit to the main menu, but rejoining the campaign just left me with no means of adding a new level or accessing any other tools.
**To Reproduce**
1. Create a new campaign.
2. Delete the only level available
3. Any options aside from "quit to menu," and "quit to desktop" available.

**Screenshots/Videos/Twitch Clips**
Didn't record it.

**Comment by ronniemoon** [comment] 2020-04-11 06:00
Confirmed

**Comment by Slytrimz** [comment] 2020-04-11 13:30
If you have multiple boards it also happens when you delete the one you are currently on.

**Comment by LuPro** [comment] 2020-04-11 22:52
looks like #5 or #20 to me - can you confirm this?

**Comment by Chezeret** [comment] 2020-04-13 15:05
Yes, it is the same problem. Sorry I didn't connect those two to my issue.

**Comment by LuPro** [comment] 2020-04-13 17:11
No problem :) I'll just close this then as it is a duplicate of the other

**Closed by LuPro** 2020-04-13 17:11 UTC
Labels: question
