### ISSUE TITLE
Open up the slab api (feature request)

### ISSUE THREAD

**Issue by c7bamford** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#996] opened 2021-06-28 03:08 UTC
It would be really beneficial for us if we were able to build our own tools to integrate with TaleSpire to create such features as procedurally generated terrain, towns and dungeons. All that would be required for these tools is a transparent api to create slabs. Some projects already exist in this niche, but it would be nice to have support from Bouncyrock in the form of documentation.

**Comment by LuPro** [comment] 2021-06-28 11:30
This is not a bug, so I'll close this issue :)
The devs are planning on doing that, in fact they have published info on how the old slab format worked (which is technically still supported), they just didn't have the time to do proper documentation on the new one yet, especially considering the format is likely to change again (once creature copy paste gets in). There's already a few procedural terrain generators out there, and I think someone reverse engineered the new slab format already as well (it's largely similar to the old format but supports more rotation options for props)

**Closed by LuPro** 2021-06-28 11:30 UTC

**Comment by c7bamford** [comment] 2021-07-11 06:45
Thanks for the reply :D
