### ISSUE TITLE
Dungeon corner tile has z-fighting issue

### ISSUE THREAD

**Issue by TuTuc0** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#981] opened 2021-06-13 16:42 UTC
When this Dungeon corner tile is placed, upper part of corner where two walls intersect, has the z-fighting issue.

Tile:

**\`\`\`H4sIAAAAAAAACzv369xFJgZGBgaGJ34Jv0K3q7pOfnYu5svVSzkgMQQAALRH4+IoAAAA\`\`\`**

**Screenshots/Videos/Twitch Clips**
![image](https://user-images.githubusercontent.com/48619042/121815461-fe532080-cc76-11eb-898a-8d5395332796.png)

**Comment by LuPro** [comment] 2021-06-13 20:28
Duplicate of #706

**Closed by LuPro** 2021-06-13 20:28 UTC
