### ISSUE TITLE
Slanted units

### ISSUE THREAD

**Issue by Madoodad** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#965] opened 2021-06-01 00:33 UTC
![image](https://user-images.githubusercontent.com/85140986/120251343-e5924600-c246-11eb-906d-88c90b9bd36a.png)
 
After dragging a player unit, and switching to grid movement, unit got stuck slanted

**Comment by LuPro** [comment] 2021-06-01 21:28
Duplicate of / Related to #791

**Closed by LuPro** 2021-06-01 21:28 UTC
