### ISSUE TITLE
Movement keys locked till mouse is used for some movement

### ISSUE THREAD

**Issue by Pruegeleisen** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#205] opened 2020-04-11 18:27 UTC
![movement_lock_example](https://user-images.githubusercontent.com/60484657/79051878-ee831b00-7c32-11ea-9aab-297f77c76020.gif)
**Describe the bug**
When loading a new Campaign the movement keys (wasd) do not work
 
**To Reproduce**
1. Load a new campaign
2. Try to use WASD to move
3. Using rotation or right-click movement resolves it for the whole campaign (double-left click does not)
4. Returning to the main menu and loading any campaign locks these keys again

**Video example**
![Uploading movement_lock_example.gif…]()

**Additional info**
Using "KeyPosé" to show the key pressings.
I hope the gif quality/size is acceptable

Edit: Fixed upload issue (somewhat), changed left/right accordingly

**Comment by jamogwe** [comment] 2020-04-11 19:22
Ditto

**Comment by LuPro** [comment] 2020-04-12 00:28
Duplicate of #130

**Closed by LuPro** 2020-04-12 00:28 UTC
