### ISSUE TITLE
stone walls

### ISSUE THREAD

**Issue by dragonbobff7** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#394] opened 2020-04-16 18:18 UTC
**Describe the bug**
Here tell us what you thought was meant to happen and then how TaleSpire vomited on itself

**To Reproduce**
1. add corner wall
2.  try to add 2x1 wall
3. it would not aline (see video)
4.is the a problem or and i still need to learn some more thing about placing things
[2020-04-16 18-55-51.zip](https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/files/4489007/2020-04-16.18-55-51.zip)

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

**Comment by LuPro** [comment] 2020-04-16 19:05
Duplicate of #143, the problem is the corner asset not being quite right.

**Closed by LuPro** 2020-04-16 19:05 UTC
