### ISSUE TITLE
Hide/Unhide bug

### ISSUE THREAD

**Issue by Cold1029** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#519] opened 2020-05-03 20:08 UTC
**Describe the bug**
Here tell us what you thought was meant to happen and then how TaleSpire vomited on itself
Used the Hide button to hide a ghost character that was not meant to be visible to the party. In GM mode I was not able to see or select the token, could not "unhide", could still pick up and move the token. 

**To Reproduce**
1. Placed spirit, undead token
2. clicked "hide" option
3. ???
4. Profit

**Screenshots/Videos/Twitch Clips**
I dun has screen capture softwares :(

**Additional context**
I wish I were more interesting.

Have a wonderful day!

**Comment by Cold1029** [comment] 2020-05-03 20:10
Nevermind, I'm a dumbass. Had to turn on GM overlay

**Comment by LuPro** [comment] 2020-05-04 13:48
Closing this as it's not a bug. The ability to move hidden tokens has been noted in another issue already

**Closed by LuPro** 2020-05-04 13:48 UTC
