### ISSUE TITLE
Accidentaly creating non-removible, non-selectable minis.

### ISSUE THREAD

**Issue by F-Barretto** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#763] opened 2021-04-16 02:07 UTC
**To Reproduce**
1. Select a mini.
2. Select another mini on the mini's menu, making sure that where you click to select you new mini is also an available place on the mat.
3. Your first mini will be placed on that spot, but will be intangible. You cannot select it and it appears as hidden on tab, but everyone can see it.

**Comment by Yogazo** [comment] 2021-04-16 06:38
Ive noticed it happens to me when i  spawn and place minis partially in an object, then im not able to interact with them.

**Comment by LuPro** [comment] 2021-04-16 10:16
Duplicate of #592

**Closed by LuPro** 2021-04-16 10:16 UTC
