### ISSUE TITLE
Random patch of 3x5 light green grass stuck on every realm/layer

### ISSUE THREAD

**Issue by davenmir** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#1001] opened 2021-07-03 23:59 UTC
**Describe the bug**
When using the build tool I made a 3x5 patch of light green grass, this some how became fused to the default layer.  I deleted the map and now every new board has the same 3v5 patch in the same spot.

**To Reproduce**
1. Open no board
2. Go into build mode
3. Use the selecting tool and cut the 3v5 patch
4. Spam paste around the original 3v5 patch then control Z however many times you pasted.
5. Original 3v5 patch stays behind.

**Comment by LuPro** [comment] 2021-07-04 12:03
Does this get fixed on restart? Also is said 3x5 grass patch also visible in the main menu?

**Comment by davenmir** [comment] 2021-07-04 14:55
This issue is fixed on restart of the application.

The 3x5 patch is only visible on the board, not any menus

**Comment by baggers-br** [comment] 2021-08-17 18:00
Cheers @davenmir. That definitely sounds like the slab preview wasn't cleared when leaving the paste tool. I haven't found a good way to replicate this issue yet (your steps were great but it didnt do it for me)

Can you trigger this bug reliably or was it a one off?

**Comment by davenmir** [comment] 2021-08-17 18:08
Sorry for my lack of update. I was able to reproduce this issue but only about half the times I tried. 

I believe there's another step to take to reproduce but it is elusive.

**Comment by baggers-br** [comment] 2021-08-17 21:24
Oh you have nothing to apologize for, it's me whos taken a *really* long time to get to these bugs.

I have just seen this bug https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/issues/989 which I was able to reproduce. It looks like there is a bug when the paste button gets involved. It's an easy one to accidentally press too.

I'll get that fixed now and hopefully it helps with this one too.

**Comment by baggers-br** [comment] 2021-08-17 22:19
#989 is fixed internally and will be in the next patch. Once that is out we can see if that helps this case too.

**Closed** 2021-12-05 12:05 UTC
Labels: bug, fixed by restart, potentially fixed in next patch
