### ISSUE TITLE
Floating above dungeon corner.

### ISSUE THREAD

**Issue by Resendez1** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#517] opened 2020-05-03 04:03 UTC
Issue where pieces placed above dungeon corner + no floor float as if a single floor piece is in the way. Tested with other corners and only seems to be affecting the dungeon tile.
![Dungeon corner float](https://user-images.githubusercontent.com/63680450/80898448-1bbe6880-8cc9-11ea-8036-ecdfe817e8e3.PNG)

**Comment by LuPro** [comment] 2020-05-04 13:47
Duplicate of #123

**Closed by LuPro** 2020-05-04 13:47 UTC
