### ISSUE TITLE
(Chimera) CTD When Upgrading Dragon Build boards in Campaign

### ISSUE THREAD

**Issue by swyndelinewriter** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#655] opened 2021-03-31 23:12 UTC
![20210331160955_1](https://user-images.githubusercontent.com/64670468/113222361-ae4deb80-923b-11eb-8bea-4c58c8315cd3.jpg)
![20210331161000_1](https://user-images.githubusercontent.com/64670468/113222366-b3129f80-923b-11eb-86f7-c927f94829ba.jpg)
![20210331161003_1](https://user-images.githubusercontent.com/64670468/113222371-b6a62680-923b-11eb-82a5-a4b57ee26f39.jpg)

**Describe the bug**
When I attempt to enter the campaign I've been working on for a year in the Dragon build Beta version I get a prompt that I have to upgrade the boards to the new format. When I click upgrade it shows a list of the boards and a progress indicator pops up for maybe two seconds before crashing to desktop.

**To Reproduce**
1. Opened Chimera build
2. Launched Campaign from Dragon Build
3. Upgrade old boards
4. TaleSpire crashed

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

**Additional context**
I really hope my campaign isn't gone for ever. All my friends are looking forward to buying the Early Access version so they can play this campaign that I've been working on for a year.

**Comment by LuPro** [comment] 2021-04-01 01:25
Duplicate of #640

**Closed by LuPro** 2021-04-01 01:25 UTC
