### ISSUE TITLE
Dungeon tile: Corner + No Floor misaligns on stacking

### ISSUE THREAD

**Issue by DugFwesh** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#448] opened 2020-04-20 20:01 UTC
When using the Dungeon Tile: Corner + No Floor and stacking them, they leave a gap between the blocks... 

![Talespire Stacking Issue](https://user-images.githubusercontent.com/63662597/79794373-60342680-830f-11ea-8a50-30c4f9c4f3e1.PNG)

**Comment by LuPro** [comment] 2020-04-21 13:25
Duplicate of #123

**Closed by LuPro** 2020-04-21 13:25 UTC
