### ISSUE TITLE
Miniture teleport mouse button is different then F1 help menu

### ISSUE THREAD

**Issue by Surrwin** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#504] opened 2020-04-28 17:08 UTC
**Describe the bug**
The F1 help menu shows that the Teleport Creature functionality should be accessible by holding Shift + Right clicking.  However, it is accessible via Shift + Left clicking.  Please update F1 help menu or change key binding.

**To Reproduce**
1. Hold Shift + Right click on a miniture
2. Miniture menu options show up
3. Right click off the miniture to close the menu options
4. Hold Shift + Left click on a miniture
5. Miniture is now in teleport mode

**Screenshots/Videos/Twitch Clips**

![image](https://user-images.githubusercontent.com/12024708/80516092-90e81180-8948-11ea-8486-e127a6ce2c7b.png)

**Comment by LuPro** [comment] 2020-04-29 00:15
Duplicate of #15

**Closed by LuPro** 2020-04-29 00:15 UTC
