### ISSUE TITLE
 Models stuck on board and unselectable

### ISSUE THREAD

**Issue by Rikid733** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#787] opened 2021-04-16 21:48 UTC
Model images get stuck on piece on parts of the board, and become un-selectable and therefore undeletable.

Happened when;

Selecting models in rapid succession, clicking them unto the board made them appear in random spots, usually clipped to existing models.

For example the rockworm thingy is stuck on the goat, and the chicken is stuck in the fence.
 
![image](https://user-images.githubusercontent.com/82681968/115088796-e5452200-9f08-11eb-8e8c-a8227df36cfa.png)

much love

**Comment by LuPro** [comment] 2021-04-17 00:58
Duplicate of #592, should be fixed in this patch as well :)

**Closed by LuPro** 2021-04-17 00:58 UTC
