### ISSUE TITLE
Selecting a Mini while you already have one selected causes the old Mini to become a permanent addition to the map

### ISSUE THREAD

**Issue by TheBestCowman** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#759] opened 2021-04-16 00:14 UTC
**Describe the bug**
Hey all, the bug is simply an undeletable mini that really ruins the atmosphere, albeit flying on a tree or standing where it shouldn't as a cause of this silly issue. Selecting a new mini while you have one moving around on your mouse causes the old mini to place where you clicked, and you can;t delete it.

**To Reproduce**
1. Select any of the Minis
2. Attempt to click on another mini
3. the mini will be placed and the new Mini will be selected, the old mini will be irremovable

![20210415181139_1](https://user-images.githubusercontent.com/82621523/114953665-155fc880-9e16-11eb-8103-c2d5c869bde1.jpg)

**Additional context**
Happened twice, just want a quick easy fix!

**Comment by LuPro** [comment] 2021-04-16 00:50
I presume this is a duplicate of #592, you need to go to the main menu and then back to the campaign and it should vanish :) If not please comment so I can reopen the issue

**Closed by LuPro** 2021-04-16 00:50 UTC
