### ISSUE TITLE
Corner bloc

### ISSUE THREAD

**Issue by tanguyp14** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#727] opened 2021-04-15 10:08 UTC
**Describe the bug**
Maybe not a bug but some bloc are not aligned. 

**To Reproduce**
Just see photos 

**Screenshots**
![image](https://user-images.githubusercontent.com/26545997/114852537-24795300-9de3-11eb-9470-197904e90624.png)
![image](https://user-images.githubusercontent.com/26545997/114852573-2c38f780-9de3-11eb-9a8f-15cbe727469e.png)
![image](https://user-images.githubusercontent.com/26545997/114852622-39ee7d00-9de3-11eb-9dac-eccb2b38a2b4.png)
![image](https://user-images.githubusercontent.com/26545997/114852658-41158b00-9de3-11eb-95d3-8e66709d924c.png)

**Additional context**
Happend on most of not "normal" wall

**Comment by LuPro** [comment] 2021-04-15 19:13
Duplicate of #21

**Closed by LuPro** 2021-04-15 19:13 UTC
