### ISSUE TITLE
Mystery Goat

### ISSUE THREAD

**Issue by RyuuDraconian** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#776] opened 2021-04-16 07:29 UTC
Just testing out the program.

Put six 8x8 grassland pieces.
Couple goats and a murloc.
Built a dice box out of castle pieces.
Started new board/realm.
One goat stayed on the new board and was not able to be deleted.

**Comment by LuPro** [comment] 2021-04-16 10:26
Duplicate of #592, should be fixed in the upcoming patch

**Closed by LuPro** 2021-04-16 10:26 UTC
