### ISSUE TITLE
Fairy forever

### ISSUE THREAD

**Issue by Zelda911911** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#726] opened 2021-04-15 09:22 UTC
I was messing around with creatures and when I was switching away from fairy to a little mushroom, a fairy was placed, even though I didn't place it. It is now is un-selectable and cannot be deleted, I have switched realms to try to escape it and is still there.

**Comment by Zelda911911** [comment] 2021-04-15 09:27
![image](https://user-images.githubusercontent.com/74081081/114846750-d5ef9880-9d91-11eb-869b-b8c3ca6feabd.png)
Can't see it but my mouse is hovering right above the stand for the fairy. I have tried every mode and the fairy.

**Comment by LuPro** [comment] 2021-04-15 09:44
Duplicate of #724 / #592

**Closed by LuPro** 2021-04-15 09:44 UTC
