### ISSUE TITLE
Hypersmall Window

### ISSUE THREAD

**Issue by RodasIsAlive** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#363] opened 2020-04-15 13:12 UTC
**Describe the bug**
I opened Talespire and after a setting change, the program window became very small, and everything is compacted. No matter what I do, it wont come back to a regular size.

**To Reproduce**
1. Within the main menu, clicked on the settings icon.
2. Once in settings, clicked on audio settings icon.
3. Changed the position in the slider.
4. TaleSpire became minuscule, and every time I try to open it again it remains the same.

**Screenshots/Videos/Twitch Clips**
![talespireerror](https://user-images.githubusercontent.com/63724925/79340566-c6453600-7f2a-11ea-9091-589f9a81dda7.jpg)

**Additional context**
I have tried to uninstall and reinstall, I have disconected the cloud service in steam, deleted everything from Talespire in my computer, uninstalled and reinstalled, I have opened the program and tried to use Alt+Enter, then it went full screen but with everything mushed together, like this:
![error2](https://user-images.githubusercontent.com/63724925/79341040-70bd5900-7f2b-11ea-9d38-0321396cbef6.png)

Please help.

**Comment by LuPro** [comment] 2020-04-15 22:19
Duplicate of #110, fix described in #55

**Closed by LuPro** 2020-04-15 22:19 UTC
