### ISSUE TITLE
Character Names Display Incorrectly (or Not At All)

### ISSUE THREAD

**Issue by Pumblechuck** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#929] opened 2021-05-13 17:23 UTC
Using the TAB key to reveal the names of miniatures, the vast majority of the minis have either no name above their head, or seem to acquire the names of other minis from the same board

1. Hold down the TAB key on a board with several named miniatures
2. Look at each mini's name; some of them should be incorrect/missing
3. This issue seems to occur based on camera position; I have been able to see different names above the same miniature depending on where my camera is positioned on the board

![image](https://user-images.githubusercontent.com/66517154/118161759-df633380-b417-11eb-85a4-14019b262355.png)

In the above screenshot, the mini who's name is 'Patron' is actually named 'Mayor Elderwood' in the GM Settings. I was able to get his name to display as 'Bard' by releasing TAB, shifting around my camera to another position, and then holding TAB again.

**Comment by LuPro** [comment] 2021-05-14 12:42
Duplicate of #913

**Closed by LuPro** 2021-05-14 12:42 UTC
