### ISSUE TITLE
Tavern Wall Corners Do Not Align

### ISSUE THREAD

**Issue by abonnell** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#416] opened 2020-04-17 21:04 UTC
**Describe the bug**
Tavern Wall corners do not align

**To Reproduce**
Place corners

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

**Additional context**
Unburden yourself of thoughts and musings here

![image](https://user-images.githubusercontent.com/62351448/79613955-5fec1f00-80b4-11ea-9168-005569ec3473.png)

**Comment by LuPro** [comment] 2020-04-17 22:24
Duplicate of #21

**Closed by LuPro** 2020-04-17 22:24 UTC
