### ISSUE TITLE
Cannot Paste - Out of Shader Slots Error

### ISSUE THREAD

**Issue by DasAmigo** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#415] opened 2020-04-17 21:01 UTC
**Describe the bug**
Here tell us what you thought was meant to happen and then how TaleSpire vomited on itself

**To Reproduce**
1. copied this https://talesbazaar.com/prefab/588
2. copy pasted a few times messing around
3. Pasting stopped working till I reloaded board. 
 
![2020-04-17 16_59_07-Window](https://user-images.githubusercontent.com/6361131/79613798-3c819e00-80cd-11ea-9574-4c8cec283a13.png)

**Comment by LuPro** [comment] 2020-04-21 23:29
Just noticed that this is a duplicate of #403

**Closed by LuPro** 2020-04-21 23:29 UTC
Labels: bug
