### ISSUE TITLE
Drag-Cloning walls misaligned after spawning. 

### ISSUE THREAD

**Issue by ShaunDave** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#36] opened 2020-04-10 21:19 UTC
Description:
When using the drag function to clone a wall tile (in this example, "Tavern Wall 01") the tile doesn't drop where expected, and seems offset by one grid location. This doesn't happen when cloning an individual tile.

Expected Behaviour:
Wall tiles spawn in line with the previous tiles.

Actual Behaviour:
Wall tiles spawn misaligned with the previous tiles, and are offset by one grid item

Steps to Reproduce:
1. Load empty build
2. Place tile "Tavern Wall 01"
3. Shift+Middle Click to begin Clone mode
4. Move mouse so that preview / placement grid lines up with previous wall tile
5. Drag a line of 2 or more tiles and let go
6. Tiles spawn misaligned.

*Screenshots:*

Step 4: Alignment
![image](https://user-images.githubusercontent.com/63476710/79023778-6b55bc80-7b81-11ea-8bd0-02e169184869.png)

Step 5: Drag selection
![image](https://user-images.githubusercontent.com/63476710/79023805-7e688c80-7b81-11ea-9d80-73698fe9fa3a.png)

Result: MisAligned
![image](https://user-images.githubusercontent.com/63476710/79023836-917b5c80-7b81-11ea-8bb8-562110b7b315.png)

Additional comment: Seems like individual cloning works fine

**Comment by LuPro** [comment] 2020-04-11 13:15
Duplicate of #17

**Closed by LuPro** 2020-04-11 13:15 UTC
