### ISSUE TITLE
Hide tool too small to select 

### ISSUE THREAD

**Issue by peramanca** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#916] opened 2021-05-10 15:52 UTC
Hide tool too small to select, can't unhide or delete the box

if it's to thin you can't select it anymore.

![123](https://user-images.githubusercontent.com/83971415/117687687-669d7680-b18e-11eb-80a5-dba793880f13.png)

**Comment by LuPro** [comment] 2021-05-11 14:36
Duplicate of #527

**Closed by LuPro** 2021-05-11 14:36 UTC
