### ISSUE TITLE
Extra copy of a creature model spawned in, but it is also unclickable, cannot delete. Unsure how to reproduce, was just messing around and populating an inn as a test drive.

### ISSUE THREAD

**Issue by Kraussgang** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#724] opened 2021-04-15 06:19 UTC
**Describe the bug**
Here tell us what you thought was meant to happen and then how TaleSpire vomited on itself

**To Reproduce**
1. Punch an ogre '...'
2. Set a chair on fire '....'
3. Tried to open a door '....'
4. TaleSpire crashed

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by alastor525** [comment] 2021-04-15 06:31
I've just came across the same issue. Im unsure how i did it but the last thing i did when it happened was click on the character in the menu with one in my hand and it seemed to happen

**Comment by JoshtheValiant** [comment] 2021-04-15 07:16
I just came in to report the same issue.  I believe it was because I placed a creature down in Build Mode, possibly specifically because I placed it behind the library tray while in build mode.

**Comment by LoneNightfury** [comment] 2021-04-15 07:30
This is reproducible when you have a character selected (ready to place) but without de-selecting, selecting a different model to place out of your library.

**Comment by george1106** [comment] 2021-04-15 07:30
Came in to report the same issue. 

Steps to reproduce the behavior:

1. Click the catalog to select a creature to spawn
2. Spawn a creature
3. Don't press Escape to remove the creature from selection
4. Select a different creature from the catalog while holding the other creature
5. You have now created the un-interactable creature as you selected another.

**Comment by LuPro** [comment] 2021-04-15 09:42
Duplicate of #592 and some more related issues, as LoneNightfury said, it should be fixed by going to the main menu and loading back in again. Nice steps for reproduction though, that will probably be helpful to fix this bug :)

**Closed by LuPro** 2021-04-15 09:42 UTC

**Comment by LuPro** [comment] 2021-04-25 18:31
Should be fixed by now, see #592
