### ISSUE TITLE
Misaligned Piece

### ISSUE THREAD

**Issue by Aziezal** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#884] opened 2021-05-01 10:25 UTC
**Describe the bug**
VERY minor issue but figured you would want to know; Tarven Corner tile 2x2 (no broom) does not line up with other Tavern tiles.

**To Reproduce**
1. Place tavern corner tile
2. Place other tavern tile
3. Notice how edge are slightly off

**Screenshots/Videos/Twitch Clips**
[TSBug 1.docx](https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/files/6409391/TSBug.1.docx)

**Additional context**
Sorry if this is a repeat or not a priority

**Comment by LuPro** [comment] 2021-05-01 23:15
Duplicate of #21

**Closed by LuPro** 2021-05-01 23:15 UTC
