### ISSUE TITLE
Stair Clipping

### ISSUE THREAD

**Issue by zhu020** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#465] opened 2020-04-22 01:06 UTC
**Describe the bug**
I was walking a hero model up the stairs and they clipped through

**To Reproduce**
1. Take the Adventurer Rotund model
2. Glide it up the stairs relatively quickly
3. Will clip after the second stair ish

**Screenshots/Videos/Twitch Clips**
![Stair clipping](https://user-images.githubusercontent.com/64113115/79929519-ed60a380-8413-11ea-870d-ecd15819294e.png)

**Additional context**
Love the program. Its wonderful. Would also love some dark vision option and fog of war <3

**Comment by LuPro** [comment] 2020-04-22 02:41
Duplicate of #24

**Closed by LuPro** 2020-04-22 02:41 UTC
