### ISSUE TITLE
Hidden minis visible to players via Tab

### ISSUE THREAD

**Issue by MallowOni** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#869] opened 2021-04-28 08:07 UTC
Regardless of whether I hide a mini individually via its Hide radial button, use a hide box, or even combine the two, players can simply hold the Tab key and see hidden minis.

**Comment by LuPro** [comment] 2021-04-28 11:51
I presume you mean just the names of the minis? if so that'd be a duplicate of #771

**Comment by MallowOni** [comment] 2021-04-28 15:19
> 
> 
> I presume you mean just the names of the minis? if so that'd be a duplicate of #771

Yes, that's the case.

**Closed** 2021-04-28 15:27 UTC
Labels: question
