### ISSUE TITLE
Camera Not Moving Upon Loading In

### ISSUE THREAD

**Issue by vampirewthbraces** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#264] opened 2020-04-12 17:49 UTC
A very minor issue. When you first load into a campaign, the camera will not move using the
QWE
ASD
keys until the camera is moved with the Right-Mouse click.

**Comment by LuPro** [comment] 2020-04-12 21:26
Duplicate of #130

**Closed by LuPro** 2020-04-12 21:26 UTC
