### ISSUE TITLE
Cannot adjust HP when an NPC attacks your Character

### ISSUE THREAD

**Issue by tinman4243** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#451] opened 2020-04-21 01:10 UTC
**Describe the bug**
Since you cannot interact with your token in turn-based mode when it is not your turn, you cannot adjust your HP when another character attacks you.  Perhaps this is intentional, but it is counter-intuitive.

**To Reproduce**
1. Enter turn based mode.
2. Attempt to change your hp and find that you cannot

**Screenshots/Videos/Twitch Clips**
None

**Additional context**
Is a fish taco shaped like a fish?

**Comment by LuPro** [comment] 2020-04-21 13:28
Most likely not a bug per se, but an oversight of the permissions for players in this case, I'll mark it as bug though as user experience wise this shouldn't be the case IMO

**Comment by jonnyree** [comment] 2020-10-05 19:47
This was addressed in update BUILD-ID: 5632745.
Thank you for reporting this!

**Closed by jonnyree** 2020-10-05 19:47 UTC
Labels: bug, potentially fixed in next patch
