### ISSUE TITLE
Corner + No Floor tile placement issues.

### ISSUE THREAD

**Issue by Ruladian** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#606] opened 2020-09-20 02:07 UTC
The **Corner + No Floor** tile in the **Dungeon** tab do not allow any other tile to be placed directly on top of them.
![Wall + Corner Bug](https://user-images.githubusercontent.com/6038597/93691475-8dd9f300-fa9a-11ea-9008-1a8960849770.png)

**Comment by LuPro** [comment] 2020-09-23 05:41
duplicate of #123

**Closed by LuPro** 2020-09-23 05:41 UTC
