### ISSUE TITLE
Autosave didn't save

### ISSUE THREAD

**Issue by arblaster** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#58] opened 2020-04-10 22:23 UTC
**Describe the bug**
I wasn't sure how to save since there was no save button and assumed it autosaved, so I renamed the map and opened a new one. Just to check I went back to the old one but the save it had made was from 1.5 hours ago and almost all my progress was lost, only thing it kept correctly was the enemies who were now floating in the air. It also didn't save the name I had changed it to.

**To Reproduce**
I don't know

**Screenshots/Videos/Twitch Clips**
![image](https://user-images.githubusercontent.com/27362854/79026919-942e7f80-7b8a-11ea-8943-5c5dfd0522c2.png)

**Additional context**
Nothing

**Comment by LuPro** [comment] 2020-04-11 20:45
Duplicate of #53, but nice extra info with the miniatures

**Comment by LuPro** [comment] 2020-10-20 11:34
As this issue hasn't been encountered in quite a while and quite a lot of issues regarding persistence have been fixed since a while already, I'll close this. If any issues regarding this pop up again, please create a new issue

**Closed by LuPro** 2020-10-20 11:34 UTC
Labels: bug, persistence issue
