### ISSUE TITLE
Text chat messages sending twice

### ISSUE THREAD

**Issue by CamoMilly** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#677] opened 2021-04-02 14:33 UTC
**Describe the bug**
When sending messages on the TaleSpire text chat, the messages came out doubled, both in the speaker bubbles and in the text chat log itself.

**To Reproduce**
Unfortunately, I'm not managing to reproduce it right now; whenever I sent a text message, it was sent twice, as seen in the picture below.

**Screenshots/Videos/Twitch Clips**
![image](https://user-images.githubusercontent.com/74841089/113423179-5e3e6880-93a4-11eb-8c12-b50755cb7d54.png)

**Comment by LuPro** [comment] 2021-04-02 15:06
I somehow managed to have that happen as well (even a triple send), but couldn't reproduce as well:
![image](https://user-images.githubusercontent.com/20774976/113427621-a924a400-93d5-11eb-808f-9a7aac851db0.png)

**Comment by MallowOni** [comment] 2021-04-03 10:13
To duplicate, and even exacerbate, this issue I just have to keep reloading the same board by choosing Go to Board from within the Board menu in the upper left.

![image](https://user-images.githubusercontent.com/63642460/113475414-28988e80-943b-11eb-9c1c-f6f5c5c9e7d1.png)
![image](https://user-images.githubusercontent.com/63642460/113475427-4a921100-943b-11eb-8529-3c7e36e52e40.png)

**Comment by LuPro** [comment] 2021-04-06 02:03
This should be fixed since the latest patch. I'll close this issue, if you run into this bug again/still please do tell so I can reopen

**Closed by LuPro** 2021-04-06 02:03 UTC
Labels: bug
