### ISSUE TITLE
Sewer Portal Doorway Tile Bug

### ISSUE THREAD

**Issue by EHCM81** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#544] opened 2020-05-18 00:41 UTC
**Describe the bug**

When I was creating a map that used the sewers tile set, I noticed that miniatures were unable to walk through the Sewer Portal Doorways. When I first did this, I had a roof for the sewers and discovered that the miniatures had no way of exiting the the sewer room into the next, outside of having the DM teleport the miniature into the room trying to be accessed.

I then removed the roof and discovered that the miniatures ignored the Sewer Portal Doorway altogether and hopped on the tile itself, bypassing the doorway altogether.

Is there any way to fix this allowing miniatures to cross through the threshold of the Sewer Portal Doorways? Maybe change the collision on that specific tile enabling miniatures to pass through?

**Screenshots/Videos/Twitch Clips**

![Sewer Portal Doorway Tile Bug 01](https://user-images.githubusercontent.com/64118405/82164452-880e9f80-9865-11ea-9bf5-f49a08c22ab7.jpg)

![Sewer Portal Doorway Tile Bug 02](https://user-images.githubusercontent.com/64118405/82164455-8b099000-9865-11ea-8c21-b912da3eaa23.jpg)

**Comment by PropForge** [comment] 2020-05-18 15:34
I believe this is a duplicate of https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/issues/185

**Comment by LuPro** [comment] 2020-05-19 16:29
As propforge said, gonna close this because of that

**Closed by LuPro** 2020-05-19 16:29 UTC
