### ISSUE TITLE
Some Floor Tiles Are Not Copied Over

### ISSUE THREAD

**Issue by Shrooblord** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#270] opened 2020-04-12 18:35 UTC
**Describe the bug**
When copying over a specific string of tiles, some floor tiles show up under the cursor, but aren't created when the copy is plopped down. See the *Additional Content* section for the string.

**To Reproduce**
1. Copy the string from *Additional Context*.
2. Paste the tiles into *TaleSpire*.
3. The template appears on the cursor. Click to place it in the world.
4. EXPECTED:  the template is plopped down.
5. RESULT: the template is plopped down, but some tiles are missing.

**Screenshots/Videos/Twitch Clips**
In the following screenshot, you can see the template hovering on my cursor, with all floor tiles intact. But you also see two attempts at plopping down these tiles, and the resulting holes in the floor.
![image](https://user-images.githubusercontent.com/3255068/79076771-ff985e80-7cfc-11ea-93dc-fef8db3f9c1f.png)

**Additional context**
Following is the offending string of tiles:
```H4sIAAAAAAAAC32YfWwURRTA586r3h9nqFEKGMATxFSifJZIg97tQStE0hbR8pViLrEoQiIYgRAS7ZEAojV6FYjWAjYoJgrUiz3CR7E3B4SAGjioX0GtgGAioXi2JFaUrjszOzsf+/Yuudzt/Pa9ee/Ne2925/TN02d9qAS9Zp7c/Muhi7M2jZjzzKQ7al/0oyNbGufHtlwbWhs7vPSz461d7Z1kbHumqOXql0eM5Lnnp/3bUfkKGds5LLZj19a+6ncX7EWLT7zXRMbWdde316++/4nE3qapgy69fOt2a2x9eVtH9Zi1VYkZxpSrC8dWk/sGn5qdW7ampeaDfOf5KeFH6nzW2Mfdka7aMRNnbvjuwM66nevqyX0l/mtdl7d9U5Fas6pvW6DkJXLftMzy83MbP6ls/3HeT9l5l1aS+872TO451J+q2BHquC8+/PDxgDXWVdNmdozsqPx05q624tcXVhLZzv3forfv7q7aN3nXphXnb0y8yxrrmz/P/3nHxlkbHm/uf3D2A4OJvuz3kdCC6vLqjUsn/Xlg1JN7iGzX5FP3/vXrzdg7Z9Jjp3XfM57c90bJiYdqh1XM7mhZXde0rqovaI0Fz52Z9NyxsoqDQxp3f9jWM+Qta2zVsaNTFw1UzUj9Nmfu8sN/mCQuXy15s7xoZNGsPUvWFjVdzp4iNmd3N9Y8tT01vTmUjDy26Ov2sDW29tXfa3o+2mFs/jtwMTFi/RfEFoRQFqHWqPU1EEqQ36jP+g2gRMY0zShjxVnO6O+zvuiAmbGv45YcIuMR8hu6DZFPhrEkllnANK3f9637cZR9yTjRy+UY66f3CRaw2H90LGld5+z5ENUZpHJEF8z6zYaoaTaQ6xjTx/SGfFSnzRJRhVk3+5GBQeYj87Vi5h/CqhyNkc0ShqazTNiCVbkESiAUpnJ+dMGOGYt1gIYzbOssjmksymJNfMcZ2fcA1T8Bs9j0GyKeiUiQ3sfZQawxJHKC++78Lx0wGww7X7DMQlQsYbMLhk9mViJZeWLf79jJv2nBwlhlxC7OeJ45LCpYUmXl14+weeJ2LpFxzOJyPW8IOw1D8YHlLmLXE2IyC9J1T2Dun8KoD9iDUduy0HwBKsfn02oMyfOpsUaI+IBh5lPWL6PNJzEDA8wAbfEra6uu+6PNW6V4FsgJ1ZYQvebzabG2+ouQE32Jyt1ZnBCsOKay/VtFfah9KUDXNmywGtP6EpvPGgtHSY3a8Y/wuIx7OImXLx5m+O3cbWleSPMsYM3HGZ/PYdR3nDk6mtRYMEvGjo62+1kDYXnMGNPpsGWjVgrG7HQYkuVYr3PY5raIYHGV5Un9cVtKY26dcQOyhfU6zlSdIVuOx1COJ6sjzjDAkrCcX2YYYGGbDY0pDMksGHPPx1leyYlQ5b5uwXKGt86UztKCJQvIaXuj4kMYkMNRb/84g+zkzGWnxCA7OYsXYJqdNHeRh505zHLIU2cG9p3vC8C6s96dAfPF2lPZngHo/OGWae8Pbkb3Iy4Hrh/29iFeQC5eQC6FPfxDrM694pL0kisTzBUXaT6XzlLBIDnuu55LA1I8NdYg+6AxGuuUh07yPwfHc8QLowWD4skZVEc5+9lNn4/EM2yzPGALZzndB2Iftp4Jo+L5RY21N+Ny/NlG1pmCGbXTWT+AJT2YkmcZbznITsRrTGdRwVxyZYJBdnIW1+2U5JKAD5ylCrCcynwyy+tyGamHqD6w53HYv9CVXqlnAbZgD//kfqb5lyDP+tjDv0SnYJp/ip26f6Smee661i8t6lZjsUu9ot4132lNO71VnW8peUaJw3L0fxyWM1k9eOSZlLsa2z9UssWVS0jquwBLejGpxiCWg22hOjlz+Z6W+hKQE7wvQfnC10/LF+v52u8wqB6cPDO8GfhcwPNMZfT518mzAnLac9YJkhOcac8FNJec/qLvOWnBoL3R6S+aLdQ2Xn+6nZJOV1ykvqTFZXprRLBcAabHRe51QeDZDcFxsXOJrK3pvKdC+5grLmmR19C6OzkPsFQBuRQsR/dwvo/B8zGmyfmYTlBuOHlvTBWQ49euXifFwrV3pMU11Av4tV6bsm1aTdP3Kuca6AXYw06ZaXbSfoYL2IlhO02ZQXZi2M6TpDaddyBVJ+vzBrjnjLrRK70DAbF23oE0Ruxw3oEA/5x3IH1tSwXT/BuXkHRq/tWpPUVhg8h5gbO2Wh3JuQQ9Rzq5ZHjL6fUgM62/PN0j5RL0HkfOE1ujA+Z45VwjQGuFn9uo50sBSc51bsN6ShY8J8qbpjjLU+VCyhmZdjZzZUU9OyMhdUvXyJB8jwhGc8KD0XgKltmWEyynMtp3w7bPPJ7sK9WKm/md9fNgXGfY8LkY1xkuoBNiXKd6HhlQdEIMFWBcZ76AToihQiyDgPPWkLW2gqVUhmS5uMICdH/gjNemzcTe6LZFkdN8b1DsVGP9zy1JDsoJ7jtkC/Zgcqw15v+5V+jUfB8n69SYj/QerlNnsp1QrHEB5tQD9qksLXRqa6v4rjN6jmJ4sKjfPjeF3ykRPnfsjK33gsH+T4j9Dwi4hR0YHAAA```

**Comment by LuPro** [comment] 2020-04-12 21:42
Likely to be a duplicate of #172.

**Comment by LuPro** [comment] 2020-04-21 23:15
Just tested this, and should be fixed - the slab pastes without any problems now. Forgot to check that when the fix for this came out, was around last Firday

**Closed by LuPro** 2020-04-21 23:15 UTC
