### ISSUE TITLE
Copy/paste large selection on-top of existing leaving gap between levels

### ISSUE THREAD

**Issue by Checkerbeard** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#424] opened 2020-04-18 16:45 UTC
**Describe the bug**
When copying and pasting a floor of a building, it pastes with an air gap of a quarter of a floor height between it and what you're trying to put it on-top of

**To Reproduce**
1: Create a ring of walls
2: Band-box the walls and copy selection
3: Press ctrl-v and attempt to place on-top of the existing structure
Result: it isn't possible to place this floor on-top of the floor below

**Screenshots/Videos/Twitch Clips**
![image](https://user-images.githubusercontent.com/63921049/79643683-0bbc6a00-819c-11ea-983e-7be12038c36d.png)

**Additional context**
This was also reproduced with a room on-top of floor tiles but the same gap was left below the floor tiles. They did, however, make it harder to see the gap from most angles, making for less useful screenshots.

**Comment by Checkerbeard** [comment] 2020-04-18 16:48
Further info:

It's the corner tiles which prevent this. I can't place anything directly on top of the 1x1 dungeon wall corners but can on top of the straight wall sections.

**Comment by LuPro** [comment] 2020-04-18 19:03
If it's just the corner tiles, that'd be a duplicate of #123. In that case I'll close this issue :)

**Closed by LuPro** 2020-04-18 19:03 UTC
