### ISSUE TITLE
Phantom Token Glitch

### ISSUE THREAD

**Issue by emptygaffney** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#592] opened 2020-08-12 17:31 UTC
This may be a specific glitch, but after placing a token, Something happened while I was going back to delete it. I'm not sure what, but it left a "copy" of the token floating above the game board that I can't interact with. On top of that, the same "phantom token" appeared in the same spot even when I switched to a different board. It disappeared after I backed out to the main menu and loaded the campaign again, but I'm worried that if it happens frequently it would be a pain to deal with, especially if it happens with larger tokens or tiles during a session.

**Comment by LuPro** [comment] 2020-08-12 18:22
I'm not sure based on the description but do you think this could be related to issue #586? They at least seem vaguely similar

**Comment by emptygaffney** [comment] 2020-08-12 21:41
The issues are the same, however I wasn't using a unique character, I was
just trying to drop a generic token onto the board. I hope this helps.

Also, just wanted to say thank you for developing this program. It already
looks fantastic, and I can't wait to see the end result.

**Comment by LuPro** [comment] 2021-04-15 09:43
Just closed an issue (#724) for being duplicate, but there were great ideas for reproducing this error - comments should continue here, but don't forget to check out the other issue for some details on this

**Comment by LuPro** [comment] 2021-04-17 01:18
This should be fixed since the latest update! Can you confirm if it works on your end?

**Comment by emptygaffney** [comment] 2021-04-17 01:45
Yes, it seems as though the bug is fixed. Thank you!

**Closed** 2021-04-17 01:55 UTC
Labels: bug, waiting on user confirmation of fix
