### ISSUE TITLE
'Ghost' model bug

### ISSUE THREAD

**Issue by KurtDaill** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#744] opened 2021-04-15 18:32 UTC
**Describe the bug**
Here tell us what you thought was meant to happen and then how TaleSpire vomited on itself
In essence, spawning models has a chance to cause a copy of that same model to spawn at an arbitrary angle and position on the board, and this copy is unable to be interacted with. The model will retain it's position if you move to a new board. The only way to remove these ghost models is a quick to main menu.
![Farmer of Doom 2](https://user-images.githubusercontent.com/31542404/114920195-2f3de300-9df7-11eb-92c0-fdcfa26f1d7e.png)
![Farmer of Doom](https://user-images.githubusercontent.com/31542404/114920209-31a03d00-9df7-11eb-8e9c-c5c48725b6f4.png)

**To Reproduce**
1. Spawn miniatures until one of them decides it's time to get a ghost brother.

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

**Additional context**
I just don't want to have to close my campaign to remove strange ghost miniatures.

**Comment by TheSchnibble** [comment] 2021-04-15 18:36
This happens when you select another mini while still having one selected.
The one you currently have selected is put down as "ghost" and your cursor now has the newly selected mini.

**Comment by mikkosaarinen** [comment] 2021-04-15 19:06
Was about to report the same thing, but glad that someone else already got here.

**Comment by Zarcand** [comment] 2021-04-15 19:35
Can confirm Reproduction is by attempting to select another miniature from the asset menu while cursor has miniature to place active. Can avoid by right clicking before selecting new miniature.

**Comment by johcker** [comment] 2021-04-15 19:36
I have the same error. The ghost token is unselectable, so I cant delete it and this can make a map unusable.

**Comment by Zarcand** [comment] 2021-04-15 19:41
> 
> 
> I have the same error. The ghost token is unselectable, so I cant delete it and this can make a map unusable.

Exiting to Menu and reloading map will clear these ghost tokens.

**Comment by LuPro** [comment] 2021-04-15 19:42
Duplicate of #592, but great that you're finding ways to replicate - will see if I can get it to replicate as well :)

**Closed by LuPro** 2021-04-15 19:42 UTC
