### ISSUE TITLE
Turn order goes wonky when killing a character

### ISSUE THREAD

**Issue by tinman4243** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#452] opened 2020-04-21 01:12 UTC
**Describe the bug**
Whenever a character is killed, the turn order seems to reset to an unknown position in the order. It's not the first position.

**To Reproduce**
1. Put a bunch of characters in the turn order.
2. Cycle through a few
3. Kill 1

**Screenshots/Videos/Twitch Clips**
none
**Additional context**
Using solar power to run air conditioning is using the sun to fight itself.

**Comment by LuPro** [comment] 2020-04-21 13:29
Duplicate of #445

**Closed by LuPro** 2020-04-21 13:29 UTC
