### ISSUE TITLE
Owner/Player client: GM overlay persist into player mode

### ISSUE THREAD

**Issue by ScottinNH** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#438] opened 2020-04-19 16:21 UTC
Owner/Player client: GM overlay persist into player mode.

**Describe the bug**
Talespire should turn off GM overlay when the player mode is activated.  

**To Reproduce**
1. Turn on GM overlay
2. Switch to player mode.  Player can see hidden creatures. 
3. After hitting tab key GM overlay mode is turned off and can not be turned back on from player mode.

Thoughts:  Would be nice to have a player overlay mode.  Similar to GM overlay mode but would not show hidden creatures.

**Comment by cbaggers** [comment] 2020-04-20 17:01
Thanks for the very clear report. I'll get on this now

**Comment by cbaggers** [comment] 2020-04-20 22:57
Got distracted with connectivity bugs. But this seems fixed internally now. 
The change will be in the next patch

**Comment by LuPro** [comment] 2020-04-21 14:15
This should be fixed now, can you check if it works for you now as intended?

**Comment by ScottinNH** [comment] 2020-04-21 14:30
Now works as intended.  Your team is doing great work!  Thank you.

**Closed** 2020-04-21 14:42 UTC
Labels: bug, reproducible, waiting on user confirmation of fix
