### ISSUE TITLE
Rotating objects 

### ISSUE THREAD

**Issue by knowhowe2** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#378] opened 2020-04-15 23:26 UTC
I suppose this is less of a bug and more of a user interface issue. My laptop doesn’t use a mouse, so there is no “middle click” button. With actions like rotating the camera, there are alternate ways to go about it (by using Q or E). There doesn’t appear to be an alternate way to rotate individual objects. I know I should probably just go out and buy a mouse, but for now, would it be possible to add an additional keyboard shortcut for rotating set pieces? 

Since this is public, if anyone else has any ideas on ways they got around the issue, I’d love to hear it! 

Thank you so much!

**Comment by LuPro** [comment] 2020-04-15 23:48
It is indeed not really a bug, the devs plan to add changeable keybindings in the future so that sort of stuff can be rebound to the user's liking. For now there's a "dirty" fix to do that though: Using AutoHotKey you can rebind buttons (mouse or keyboard) to others, ask around in the discord, there's someone who made a script you can use that auto detects if talespire has focus and only applies the key rebind if it has focus.

Gonna close this though as it is not a bug per se

**Closed by LuPro** 2020-04-15 23:48 UTC
