### ISSUE TITLE
Window mode blow out

### ISSUE THREAD

**Issue by frankie-break-bone** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#547] opened 2020-05-20 20:37 UTC
**Describe the bug**
In the options menu of the title screen, there is a settings menu. In the settings menu, there are GAME SETTINGS. In the DISPLAY SETTINGS there is an option to toggle window mode. I clicked on this, the game UI blew out off the screen and there is no way way to change it back, because the setting is now off screen.

This setting seems to be tied to my Steam account, somehow - I tried uninstalling the app, then completely uninstalling Steam and reinstalling both. But when I open Talespire, it's still blown out, and I can not do anything with the app.

**Screenshots/Videos/Twitch Clips**
![image](https://user-images.githubusercontent.com/65683228/82494613-da46ff00-9ab7-11ea-8acb-ab0722ccafe8.png)

**Additional context**
Is there screen-select accessibility in Talespire? If not, I might be boned here... I just opened the app for the first time ever, and I never got to try it out - this was one of the first things I did. Can someone reset my user data, or do I need to contact Steam?

I bought 3 keys and a new machine just to run Talespire. Now I've got... nothing :(

**Comment by LuPro** [comment] 2020-05-22 14:49
Duplicate of #318, see comments in #55 for a fix for this problem

**Closed by LuPro** 2020-05-22 14:49 UTC
