### ISSUE TITLE
Floor disappears somehow under the door

### ISSUE THREAD

**Issue by creadth** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#386] opened 2020-04-16 14:39 UTC
**Describe the bug**
Doors cause floor disappear

**To Reproduce**
1. Place a single tile (I tried dungeon small cells and 2x2 dungeon)
2. Place door above (I tried dungeon door, double dungeon door, peasant door)
3. Place others tiles adjacent to that construction
4. Select everything and copy as a slab
5. Paste. Floor is missing.

[videos.zip](https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/files/4487816/videos.zip)

**Comment by tvgazza911** [comment] 2020-04-16 14:44
Looks to be a duplicate of #172

**Comment by LuPro** [comment] 2020-04-16 18:07
As discussed in the discord, likely the same issue as #172, I'll leave it up in case it's something different after all

**Comment by LuPro** [comment] 2020-04-21 23:28
Missed this one back at the update; Was fixed in Friday's update, gonna close it

**Closed by LuPro** 2020-04-21 23:28 UTC
Labels: potentially fixed in next patch
