### ISSUE TITLE
Flying Player Token In All Boards

### ISSUE THREAD

**Issue by johnfercher** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#731] opened 2021-04-15 13:30 UTC
**Describe the bug**
I was doing the tutorials and tried to add a player token (a cat). The issue is that the token doesn't touch the ground and someway I cannot interact with it. And this token appear in all boards.

**To Reproduce**
I was not able to do it again.

**Screenshots/Videos/Twitch Clips**
![image](https://user-images.githubusercontent.com/4752636/114876885-23d9c000-9dd5-11eb-903c-b27890f09982.png)

**Additional context**
* The cat has gonne when I reopened the game.
* The game is awesome =)

**Comment by LuPro** [comment] 2021-04-15 19:16
I think this might be a duplicate of #592 - does this go away after you go to the menu and back?

**Comment by johnfercher** [comment] 2021-04-17 21:36
Yes I think is the same issue.

**Comment by LuPro** [comment] 2021-04-18 00:13
Is it fixed for you now? The bug should be fixed by now

**Comment by johnfercher** [comment] 2021-04-18 15:34
This bug didn't show up anymore to me.

**Closed** 2021-04-18 21:17 UTC
Labels: waiting on user confirmation of fix
