### ISSUE TITLE
Stairs are funky

### ISSUE THREAD

**Issue by Carter2083** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#206] opened 2020-04-11 18:32 UTC
**Describe the bug**
I kind of expected my character to not phase through the walls despite him not casting stone meld. In real talk, my character can phase into a stair block and then become impossible to select as he is actually inside of the stair block.

**To Reproduce**
1. Drag character into a stair block.
2. Phase through through stair case and then stair block.
3. Try to re select character who is inside of the block. (Cannot re select them unless a part of them are showing)

**Screenshots/Videos/Twitch Clips**

**Additional context**
I think it is a brilliant app! ^^ I have been trying to capture and recreate some bugs, I have not sussed how to put a screenshot here but I will figure that out eventually! Good job!

**Comment by BlappoSpawn** [comment] 2020-04-11 19:03
Dupe of #24

**Comment by Carter2083** [comment] 2020-04-11 19:09
Sorry. I am new to this. I don't really understand how GitHub works, I'll be sure to check through the other errors in the future.

**Closed** 2020-04-11 19:09 UTC
