### ISSUE TITLE
Talespire Filter Term Bug

### ISSUE THREAD

**Issue by AlineLion** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#359] opened 2020-04-15 08:36 UTC
**Describe the bug**
If you use a filter in the search bar and then leave to the main menu, if you then open a campaign, the filter will still be active and you will be unable to delete it.

**To Reproduce**
1. Open campaign
2. Search in filter on Building Asset tab
3. Exit to main menu
4. Open (any)
5. Return to building asset tab

**Screenshots/Videos/Twitch Clips**
[https://youtu.be/syNjttqCnyk](url)

**Additional context**
Just so you know, the bug does not appear as long as you reopen TaleSpire :). 

Thanks so much you guys! This game is a dream come true. 

EDIT: I commented below about an easy fix (though I did it on accident).

**Comment by AlineLion** [comment] 2020-04-15 08:42
I messed around a little more and discovered that this really only seems to be an aesthetic bug (I know nothing about coding so I don't know what else to call it haha). What I mean is that if you press backspace on the filter search bar it resets everything. 

[https://youtu.be/EKdVOlje_-0](url)

**Comment by LuPro** [comment] 2020-04-15 23:50
Duplicate of #103 / #329

**Closed by LuPro** 2020-04-15 23:50 UTC
