### ISSUE TITLE
Wooden fences dont fit together

### ISSUE THREAD

**Issue by iiAnzac** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#238] opened 2020-04-12 03:52 UTC
Was creating an animal pen, the wooden fences in the props tab do not fit together, so if you place a straight fence and then place a corner fence, they do not slot together, they aren't aligned so there is a considerable gap.

**Comment by talesparrow** [comment] 2020-04-12 04:10
I am also having the same issue.
![fencing_bug](https://user-images.githubusercontent.com/63529576/79060345-986da200-7c49-11ea-852f-b1151ecd4cb2.png)

**Comment by LuPro** [comment] 2020-04-12 11:25
Duplicate of #48, though in a seemingly more extreme way? The gap seems larger than in #48

**Comment by qu181** [comment] 2020-04-14 18:56
Just thought I'd add some more info. Its impossible to make a square. You can see the tile is like a 1.9 x 1.9 not a 2x2. Not only that but the fence even shifts into the other gid when you place it.

![Capture](https://user-images.githubusercontent.com/63611455/79262847-e9ef7a00-7e5f-11ea-881d-ef75157422f7.JPG)

**Comment by jrwillette** [comment] 2020-04-14 21:27
"Stone Wall - Corner 02" Has the same issue as this.

**Comment by LuPro** [comment] 2020-04-18 12:36
Last update this was (mostly) fixed, see #417 for remaining issue

**Closed by LuPro** 2020-04-18 12:36 UTC
Labels: asset issue
