### ISSUE TITLE
Deleting second asset 'Castle Floor 3' on map crashes program (Windows 7)

### ISSUE THREAD

**Issue by MikeMyler2** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#7] opened 2020-04-10 19:40 UTC
**Describe the bug**
After laying down two 'Castle Floor 3" assets (not copying an asset), when the first is deleted it crashed the program and corrupted the project file.

**To Reproduce**
1. Open a new project
2. Add two 'Castle Floor 3' assets
3. Delete the second asset
4. TaleSpire crashes

**Screenshots/Videos/Twitch Clips**
Unable to obtain.

**Additional context**
So far functions nicely in Windows 7 (music works, UI is snazzy).

**Comment by LuPro** [comment] 2020-04-11 10:32
Seem to be unable to reproduce this  (Windows 10) - might be some oddity with windows 7? The game is not officially tested on that IIRC.

**Comment by LuPro** [comment] 2020-05-26 15:31
The latest update introduced a likely fix for this, could you check if it works for you now?

**Comment by MikeMyler2** [comment] 2020-06-02 04:31
Yup!
![image](https://user-images.githubusercontent.com/63473946/83480063-61a55280-a468-11ea-8bc4-ce542be9addc.png)

**Closed** 2020-06-02 20:34 UTC
Labels: bug, corrupts save
