### ISSUE TITLE
Bug - Token Names not showing up correctly

### ISSUE THREAD

**Issue by Artelmis** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#945] opened 2021-05-17 23:31 UTC
**Describe the bug**
When holding tab to view character names, sometimes the name doesn't show, sometimes it shows the wrong thing. 

Edit - this seems to somewhat correct itself if the program is closed, but will manifest again when swapping between boards

**To Reproduce**
Place several minis
rename minis
hit tab to view names

**Screenshots/Videos/Twitch Clips**
![image](https://user-images.githubusercontent.com/84357018/118568400-c0c9a900-b745-11eb-9c4f-2d4a83e98a9a.png)
in this image, you see midwife (labeled correctly) and Cletus (incorrectly, as that's supposed to be the large guy with the mug)
![image](https://user-images.githubusercontent.com/84357018/118568732-7268da00-b746-11eb-9978-ac41bb10d5df.png)
Here you see several tokens missing names, and "baby oil" (sorry about that one) being associated with the wrong token)

**Additional context**
it seems to happen on old or new maps. the token's name (when viewed with GM tools) shows correct, but the popup names aren't accurate. it seems to be VERY inconsistent - reloading the board will often just shuffle the issue around.

**Comment by ugly2632** [comment] 2021-05-17 23:35
I have never had that happen to me, but I havent played with this many minis before

**Comment by Artelmis** [comment] 2021-05-18 00:43
> I have never had that happen to me, but I havent played with this many minis before

That first image is from a board with 7 minis not counting PCs (which aren't there as i'm building the map)

**Comment by LuPro** [comment] 2021-05-20 13:44
Duplicate of #913

**Closed by LuPro** 2021-05-20 13:44 UTC
