### ISSUE TITLE
IDEAS POST?

### ISSUE THREAD

**Issue by DRPAYNE244** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#902] opened 2021-05-06 23:40 UTC
To whom it may concern:

I have really enjoyed the game in the first few hours. I look forward to hosting and joining DnD campaigns in the future. I wanted to see what you all though about opening a feed for an open dialog about game improvements/ concepts. ( not just bugs/ glitches).

Thoughts?

Here are a few ideas that I wanted to get some feed back about. (I hope no offence comes to anyone on the dev. staff.)

- There should be exterior walls vs. interior walls. Interior wall should be very thin so they can be used on a 5ft scale. Exterior walls are too think to be used inside the houses.
- Trees should be able to be build on a click and drag, just like the tiles are.
- Can we get hex tiles also?
- Can we change the scale of the tiles to make the 1/4 mile tiles for large maps?
- Can doors auto reset closed, or a prompt to close all doors on the map?
- Player controls allows the character to jump over walls and doors, can we limit character jump height?
- Can we load a map full of tile blocks that we can dig away at to carve passages and other underground features? ( MINE CRAFT FLASH BACK.LOL)

**Comment by LuPro** [comment] 2021-05-07 18:48
Feedback/feature requests are better suited in the [discord](https://discord.gg/talespire), I'll go through them here as well though:

- The devs said they won't do *paper* thin walls as it doesn't mesh well with the rest of the artstyle - technically it's possible they might make thinner (but not paper thin) walls, but I personally wouldn't expect it (would be a big increase in asset numbers). However, once the modding tools come out I fully expect people to make thinner walls as mods. Additionally, you can check out the [Asset Request](https://github.com/Bouncyrock/TaleSpire-Beta-AssetRequests/issues) page where you can drop that request so the devs can gauge how popular that is (not a guarantee it will come into the game, the devs still have a vision on where this game should go)
- One of the drawbacks/compromises the devs had to take for props to be free place and have more rotation than tiles is to not have the click and drag placement. Doesn't mean it won't ever be implemented for those, but I don't think it's in the plans right now (might be wrong on this though)
- They said they'd love to look into support for hex systems, but it's a huge task as many very fundamental systems of the game are not initially designed for it. According to the [FAQ](https://talespire.com/faq) they are "designing systems with this feature in mind", but "it's a big task, so definitely a post-release feature" (So if it happens then in the far future, not short term)
- You can't (and won't be able to) change the scale of tiles or props, however you can change the scale of minis in relation to the tiles and props and you can change your ruler scale easily to whatever size you want; it's your choice whether a tile is 5 feet, 2  meters, 4.5 nautical miles, 3.98 parsec, 2 millimeters, etc. A bunch of people have already been building maps in "reduced scale" to look like overworld maps or like "1:2 scale" cities and it's working rather well.
- That is something that I'm fairly certain will get worked on, tooling overall will be tweaked further
- Technically you can already simply start building "higher up" so you can build down. You will *never* get an option to fill an "entire map up to height X with tiles" as this would absolutely *kill* performance. However, the devs have been talking about "foam terrain" which you'll be able to carve into and create more organic shapes in the future so you can build large natural environments easier, quicker, more beautiful and with less performance hit. This will also allow carving into the foam for underground sections

Also: no offence taken, and I'm sure the devs feel the same :) It's great people are using TaleSpire and wanting it to become bigger and better and feedback is super important to getting a better overall experience.

PS: I'll close this as it's not a bug report, if you want to discuss some points please do check in on the discord, it's super active with many really nice and helpful people :)

**Closed by LuPro** 2021-05-07 18:48 UTC
