### ISSUE TITLE
Hide Volumes

### ISSUE THREAD

**Issue by Natharu** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#961] opened 2021-05-28 04:35 UTC
**Describe the bug**
Was learning how to use hide volumes and placed one, and instead of deleting it i just minimized it to  it minimum vertical volume. i was then unable to re-select it or delete it, it then cause my building to have hidden parts permanently. i choose to delete the map as a whole as it wasnt important
![20210527223338_1](https://user-images.githubusercontent.com/84952734/119929920-aa88cd80-bf3b-11eb-9dfd-7039f640db5a.jpg)
 

**To Reproduce**
create hide volume
minimize to its lowest vertical volume.

**Comment by ugly2632** [comment] 2021-05-28 21:34
> 
> 
> **Describe the bug**
> Was learning how to use hide volumes and placed one, and instead of deleting it i just minimized it to it minimum vertical volume. i was then unable to re-select it or delete it, it then cause my building to have hidden parts permanently. i choose to delete the map as a whole as it wasnt important
> ![20210527223338_1](https://user-images.githubusercontent.com/84952734/119929920-aa88cd80-bf3b-11eb-9dfd-7039f640db5a.jpg)
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> create hide volume
> minimize to its lowest vertical volume.

I was not able to recreate this bug. Every time I go into GM View, then press "Edit Hide Volumes", I see the Hide Volume area pop up, even though it is pancake thin. Can you confirm that you've clicked "Edit Hide Volumes" in the GM View tab and that you cannot see the Hidden Volume pop up?

**Comment by Natharu** [comment] 2021-05-28 22:26
Yes I did select the edit hide volumes and I could no longer see or select the hide volume Sent from Mail for Windows 10 From: ugly2632Sent: May 28, 2021 3:34 PMTo: Bouncyrock/TaleSpire-Beta-Public-Issue-TrackerCc: Natharu; AuthorSubject: Re: [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker] Hide Volumes (#961) Describe the bugWas learning how to use hide volumes and placed one, and instead of deleting it i just minimized it to it minimum vertical volume. i was then unable to re-select it or delete it, it then cause my building to have hidden parts permanently. i choose to delete the map as a whole as it wasnt importantTo ReproduceSteps to reproduce the behavior:create hide volumeminimize to its lowest vertical volume.I was not able to recreate this bug. Every time I go into GM View, then press "Edit Hide Volumes", I see the Hide Volume area pop up, even though it is pancake thin. Can you confirm that you've clicked "Edit Hide Volumes" in the GM View tab and that you cannot see the Hidden Volume pop up?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ugly2632** [comment] 2021-05-28 22:46
> Yes I did select the edit hide volumes and I could no longer see or select the hide volume 

10-4

**Comment by LuPro** [comment] 2021-05-29 15:41
Most likely a duplicate of #527 but very interesting to see that it doesn't happen every time (with @ugly2632 not being able to replicate it). I'll admit that I didn't test it myself yet, so I didn't know it's just a "sometimes" issue.

**Closed by LuPro** 2021-05-29 15:41 UTC

**Comment by cbaggers** [comment] 2021-05-31 20:57
I've been able to reproduce this and will be logging the progress on #527 
Thanks to everyone for the excellent work reporting this. It made the process very quick
