### ISSUE TITLE
Photo mode export function is absolutely bonkers

### ISSUE THREAD

**Issue by Dustdown** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#908] opened 2021-05-09 02:17 UTC
**Describe the bug**
My photo mode does not render anything the proper way. Items are missing, I'm under water or the entire scene is foggy in the final screenshots. There always seem to be a different bug.

**To Reproduce**
1. This applies to all boards I've made in Talespire. 
2. It happens in Photo Mode when I try to get a photo. 
The actual experience of the photo mode itself is pretty good. The only problem I have is when I try to actually produce something. :-) 

**Screenshots**

Docks with figures. (Using PRTSCR and Photoshop)
![1a dock scene closeup via screenshot](https://user-images.githubusercontent.com/83892534/117558255-8b7bd780-b030-11eb-85aa-d3d276d62ee6.jpg)
Same scene with photo mode
![1b dock scene closeup via photo mode](https://user-images.githubusercontent.com/83892534/117558258-8cad0480-b030-11eb-8470-54ff8c8ee3f3.png)

Docks- (Using PRTSCR and Photoshop)
![2a dock scene via screenshot](https://user-images.githubusercontent.com/83892534/117558260-90d92200-b030-11eb-98b3-9e8d5b4d709e.jpg)
Same scene with photo mode
![2b dock scene via photo mode is underwater](https://user-images.githubusercontent.com/83892534/117558313-3d1b0880-b031-11eb-84b2-6b0a8824ef29.png)

Mountain build (Using PRTSCR and Photoshop)
![3a-mountain-home via screenshot](https://user-images.githubusercontent.com/83892534/117558339-718ec480-b031-11eb-9597-2ccdaefb5d6e.jpg)

And with photo mode:
![3b mountain home via photo mode](https://user-images.githubusercontent.com/83892534/117558340-72275b00-b031-11eb-8dcc-ab721eeb59a6.png)

Keep up the good work!

**Comment by LuPro** [comment] 2021-05-09 03:20
Duplicate of #676

**Closed by LuPro** 2021-05-09 03:20 UTC
