### ISSUE TITLE
Dungeon corner pieces not stacking correctly

### ISSUE THREAD

**Issue by CosmiVox** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#626] opened 2020-11-11 04:04 UTC
**Describe the bug**
Here tell us what you thought was meant to happen and then how TaleSpire vomited on itself

I am using the corner pieces from the dungeon set to create a multi story building. I was expecting to be able to stack the dungeon corner with the floor first and then the dungeon corner without the floor next without any gaps. However, I discovered that the dungeon corner piece without a floor creates a invisible barrier on top of it.

**To Reproduce**
1. Place the dungeon corner piece without the floor
2. Place anything on top of the dungeon corner piece without the floor
3. There is an invisible space between the two pieces.

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!
![image](https://user-images.githubusercontent.com/59884418/98764073-a5e63880-23a0-11eb-90f1-cea37912abe1.png)

**Comment by LuPro** [comment] 2020-11-14 20:00
Duplicate of #123

**Closed by LuPro** 2020-11-14 20:00 UTC
