### ISSUE TITLE
system mouse button setting not respected

### ISSUE THREAD

**Issue by sansorge** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#617] opened 2020-10-22 16:22 UTC
**Describe the bug**
Talespire does not respect the system mouse button settings, but in an inconsistent way that makes the entire thing unusable if your system settings are not the default. This is an accessibility issue for people like me with wrist problems.

**To Reproduce**
1. in system settings, set your primary button to "right"
2. launch Talespire
3. open a campaign, go into build mode. note that mostly, continuing to use the left button will work, but sometimes you'll need to use the right button.
4. try to lay down any tile. this is now impossible.

**Additional context**
I backed the kickstarter and I'd really love to start using Talespire, but as it stands it is unusable.

**Comment by LuPro** [comment] 2020-10-23 12:31
Duplicate of #136. Thanks for reporting nevertheless :)

**Closed by LuPro** 2020-10-23 12:31 UTC
