### ISSUE TITLE
Placing multiple objects with mouse drag crashes the game and corrupts the campaign file

### ISSUE THREAD

**Issue by SyfleNov** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#87] opened 2020-04-11 00:01 UTC
Placing multiple objects with mouse drag crashes the game and corrupts the campaign file. If you try to place an object and attempt to do the drag option to place multiple copies. It crashes the game, and attempts to go back to the campaign is corrupted.

**Comment by PolyurethaneNinja** [comment] 2020-04-11 02:20
I'm having this problem as well. The first couple of times, it didn't corrupt the campaign, but it now has corrupted two in a row. Happens with any tile I've tried, but only when dragging. Doesn't happen when placing a single tile at a time.
1. Start new campaign.
2. Select a tile
3. Drag the tile
4. Game crashes

**Comment by SyfleNov** [comment] 2020-04-11 14:11
This is my specs, my buddy who was playing this with a laptop was able to do this action no problem. I am unsure what might be the issue, but just in case.

AMD Athlon II X4 645 4 core 3.2 ghz, DDR3 1866mhz 8gbs, Nvidia Geforce GTX 660 2gb

**Comment by DragonKitten** [comment] 2020-04-11 15:57
also having that issue. my specs are 
AMD Phenom II x4 955 4 core 3.2 GHz, 8GB DDR3, AMD RX 480 8GB

**Comment by PolyurethaneNinja** [comment] 2020-04-11 16:03
My specs:
Windows 10, Intel Core 2 Quad Q6600 2.4 GHz, 8 gb RAM, Nvidia GeForce GTS 240, DX12

**Comment by LuPro** [comment] 2020-04-11 22:13
Seems similar to #12, but very interesting extra info, especially since my working theory was it could have been due to Windows 7 - but now there's a confirmed windows 10 case as well. Might not be the same error, but they're similar

**Comment by SyfleNov** [comment] 2020-04-12 00:40
My system is also running windows 10 just to add.

**Comment by SyfleNov** [comment] 2020-04-12 01:12
I am also using a HDD instead of an SSD, I don't know if that might be an issue?

**Comment by PolyurethaneNinja** [comment] 2020-04-12 10:19
I have a SSD, so that's not the issue.

I'm also having issue #228 

I tried redownloading and reinstalling the program, no difference, same with shutting down and restarting my computer.

**Comment by sviper7** [comment] 2020-04-12 11:17
I also have this issue (and #228, #114, #87, #12, #7).  The corruption of the campaign does not happen every time, but seems to be the majority of times.
 
This is on Windows 10 (1903), AMD Phenom II X6 1090T, 16GB RAM, Geforce GTX 1070, OS and software on SSDs.
I’ve attached a DXDiag file in case it is of use, and note that at the bottom I see the following Windows Error Reporting entry:
+++ WER9 +++:
Fault bucket 1246774689134558514, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: TaleSpire.exe
P2: 2019.3.0.40491
P3: 5debc82c
P4: lib_burst_generated.dll
P5: 0.0.0.0
P6: 5e90bd22
P7: c000001d
P8: 000000000000c0f4
P9: 
P10:
![2020-04-12 12_05_57-TaleSpire](https://user-images.githubusercontent.com/61346961/79067467-6c890580-7cb7-11ea-99b6-d57264053872.png)
[DxDiag.txt](https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker/files/4466208/DxDiag.txt)

**Comment by DragonKitten** [comment] 2020-04-12 11:40
I am starting to see a pattern: could it be an issue with older (amd) cpus?

**Comment by sviper7** [comment] 2020-04-12 11:42
It seems to affect some intel CPUs as well, but I had wondered if it was some instruction set not supported. Pure conjecture though.

**Comment by LuPro** [comment] 2020-04-12 11:45
generally older CPUs though - graphics card are from all eras, but CPUs are exclusively old ones (10+ years) in the reports. Could be just correlation, not causation, but it's definitely interesting

**Comment by sviper7** [comment] 2020-04-13 16:50
Did a little bit of research on the error that dxdiag had pointed to that seems to indicate that the issue may well be due to older CPUs not supporting one of the needed instruction sets.  Event viewer shows the following:
Faulting application name: TaleSpire.exe, version: 2019.3.0.40491, time stamp: 0x5debc82c
Faulting module name: lib_burst_generated.dll, version: 0.0.0.0, time stamp: 0x5e933e2e
Exception code: 0xc000001d
Fault offset: 0x00000000000016d7
Faulting process ID: 0x52e4
Faulting application start time: 0x01d611b2b79066da
Faulting application path: D:\Games\Steam\steamapps\common\TaleSpire\TaleSpire.exe
Faulting module path: D:\Games\Steam\steamapps\common\TaleSpire\TaleSpire_Data\Plugins\lib_burst_generated.dll
Report ID: 116f01f1-46bc-4708-9683-1bf28f7f52c9
Faulting package full name: 
Faulting package-relative application ID: 

Doing a quick google search returned a few results, including this one, which the developer agrees that the problem is due Burst to needing SSE4 instructions.
https://steamcommunity.com/app/671440/discussions/1/2789318172117540859/

**Comment by LuPro** [comment] 2020-04-13 17:18
This is great stuff! Thanks for the technical details, looks like this might be our problem.

**Comment by SyfleNov** [comment] 2020-04-13 18:54
Thanks sviper7! Hopefully the Dev's might find a work around that won't affect others peoples performances just for us older hardware users.

**Comment by cbaggers** [comment] 2020-04-25 00:51
I've upgraded Unity's Burst package to a preview version that seems to give us SSE2 fallback support. This will be in the next patch, so hopefully we'll see some progress on this issue then.

Thanks to everyone for collating all this data and working out so many of the details. You rock!

**Comment by cbaggers** [comment] 2020-04-27 22:43
https://bouncyrock.com/news/articles/talespire-dev-log-174

**Comment by sviper7** [comment] 2020-05-26 11:45
Today’s update which contains the fix for this seems to be working (only had time for a quick test though unfortunately).

**Comment by LuPro** [comment] 2020-05-26 15:28
The latest update should have the fix in now, please check if it works for you now

**Comment by SyfleNov** [comment] 2020-05-27 04:14
This update fixed all my issues now!

**Comment by PolyurethaneNinja** [comment] 2020-05-27 11:24
This update fixed my issue as well on my Pentium processor computer! So excited to try it out!

**Comment by LuPro** [comment] 2020-05-29 15:15
Based on reports this seems fixed now, if any of you still have related problems please report them do I can reopej the issue if needed

**Closed by LuPro** 2020-05-29 15:15 UTC
Labels: bug, corrupts save, waiting on user confirmation of fix
