### ISSUE TITLE
Board Update Failed error after CRTL+C on large board

### ISSUE THREAD

**Issue by itguy890** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#430] opened 2020-04-19 01:34 UTC
**Describe the bug**
I hit CRTL+C and then the board crashed and this error message come up. Mind you, I tried to copy the rather large board out to notepad and it said the file was too big at 34kb, max was 30kb.

**To Reproduce**
1. Copied original board and it as too big at 34kb
2. Tried to delete some extra tiles, to make the file smaller
3. Did another CRTL+C and then got error message in screenshot

**Screenshots/Videos/Twitch Clips**
![image](https://user-images.githubusercontent.com/63676300/79677174-5b129280-81bc-11ea-8034-8567f9426c5a.png)

**Additional context**
Keep up the awesome work! Having so much fun :).

**Comment by LuPro** [comment] 2020-04-19 02:59
Duplicate of #8

**Closed by LuPro** 2020-04-19 02:59 UTC
