### ISSUE TITLE
"Ghost" creatures placed when selecting other creature

### ISSUE THREAD

**Issue by rymddjur** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#751] opened 2021-04-15 20:49 UTC
**Describe the bug**
Trying to switch between different creatures in the menu and it places a "ghost" of the previous creature that can't be removed

**To Reproduce**
1. Open menus
2. Open library
3. Select a creature
4. Select a different creature

**Screenshots/Videos/Twitch Clips**
https://youtu.be/bHowaR50THY

**Additional context**
Grrrrrrrrrrrrrrrr
Also visible in the video is that there is no cursor when in the creature library. Might be related, idk.

**Comment by LuPro** [comment] 2021-04-15 22:12
Duplicate of #592, thanks for the great reproduction steps though :)

**Closed by LuPro** 2021-04-15 22:12 UTC
