### ISSUE TITLE
Light showing even when hiden

### ISSUE THREAD

**Issue by Kensuke4k** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#497] opened 2020-04-26 20:53 UTC
**Describe the bug**
even when hidden, the cast light are still visible to players.

**To Reproduce**
1. put some torch on your map
2. toggle their visibility off

**Screenshots/Videos/Twitch Clips**
![20200426175120_1](https://user-images.githubusercontent.com/64372707/80319493-dab8e680-87e6-11ea-89d5-7574cfdc3f59.jpg)

**Comment by LuPro** [comment] 2021-04-25 11:39
Duplicate of #314

**Closed by LuPro** 2021-04-25 11:39 UTC
