### ISSUE TITLE
Graphics error

### ISSUE THREAD

**Issue by ScottinNH** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#494] opened 2020-04-25 17:43 UTC
Observed error:  Some odd graphics rendering error.

**To Reproduce**
1. Move around map
2. Only in particular area
3. From particular angles
4. Not repeatable, after closing TS down to desktop and restarting.

Screen shot:
![Talespire graphic error 001](https://user-images.githubusercontent.com/50643901/80286383-19707300-86f9-11ea-8836-d4decb12a86a.jpg)

Video of issue:
https://drive.google.com/open?id=1Vdb1oPRCiejUx1G6gdjRaz7_rb7yiVjH

**Comment by LuPro** [comment] 2020-04-26 16:38
Duplicate of #42

**Closed by LuPro** 2020-04-26 16:38 UTC
