### ISSUE TITLE
Miniatures sink through Dungeon stairs

### ISSUE THREAD

**Issue by TheHolographicP** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#405] opened 2020-04-17 05:33 UTC
**Describe the bug**
A set of ascending stairs swallowed a mini as I dragged it up.
Seems to happen if you drag quickly. (See video)

**To Reproduce**
1. Place a set of stairs two tiles wide, with a second set on some stair blocks
2. Dragging a mini up the staircase results in it falling into the middle and getting stuck

**Screenshots/Videos/Twitch Clips**
https://youtu.be/JAuPFZy7Dfo

**Comment by LuPro** [comment] 2020-04-17 11:57
Duplicate of #24

**Closed by LuPro** 2020-04-17 11:57 UTC
