### ISSUE TITLE
Waiting for the Adventure to begin...Forever

### ISSUE THREAD

**Issue by TheLDSmissionary** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#119] opened 2020-04-11 03:27 UTC
**Describe the bug**
World building with my wife (we both have copies) and basically the bug is that it's stuck on the "Waiting for the Adventure to begin" I can see some shadows and some lighting but neither of us can start continuing our build

**To Reproduce**
We were building a tavern and a stable with grass tile, standard tavern tiles and props, after a session, she logged off, and tried logging in after a few hours, and now it's just stuck.

**Screenshots/Videos/Twitch Clips**
![image](https://user-images.githubusercontent.com/39438402/79034225-45bcb900-7b69-11ea-9dd7-37ad91a7c8d0.png)

**Additional context**
Super excited to be a part of this beta! Told all my friends (we got two copies) and I know at least 3 copies my friends bought. Woo!

**Comment by xRinzler** [comment] 2020-04-11 09:41
I had the same issue and posted about it before I saw your post, hopefully this gets fixed very soon. This makes the program completely unplayable.

**Comment by Keksader** [comment] 2020-04-11 15:35
Same issue, me and my friend were working on a map(I was host) and I logged out first and now I can't get in

**Comment by ericdrejza** [comment] 2020-04-11 16:13
**Bug:** Same issue here too.  I can still highlight creature tokens (both hidden and revealed) with TAB (GM view), and I can interact with creature tokens (move and wheel options) and atmosphere blocks (wheel options (editing an atmosphere block does nothing in this state)).

**Reproducing:** I was creating a burial in a cemetery (tiles, creature tokens, and GM blocks included: sparse grass tiles, dirt, dirt piles, gravestones, dungeon tiles (for the crypt), metal gate, stone wall and corner wall, villager tokens, zombie tokens, two atmosphere blocks, and a cut scene block).  I didn't log out, I only exited the application a couple of times.  I was able to return to the map before this issue started, but since the issue has started, I have not been able to return to a fully functioning map.

**Screenshots:**
Overall Issue:
![20200411115417_1](https://user-images.githubusercontent.com/37117264/79048491-69284800-7beb-11ea-92fa-e28f4ff85180.jpg)

GM view partially working:
![20200411115330_1](https://user-images.githubusercontent.com/37117264/79048505-7d6c4500-7beb-11ea-8ad0-6e99ebb6ffa5.jpg)

Able to select the atomosphere blocks:
![20200411115340_1](https://user-images.githubusercontent.com/37117264/79048506-7e9d7200-7beb-11ea-9de5-c533ed47ab96.jpg)

Able to move tokens around:
![20200411115725_1](https://user-images.githubusercontent.com/37117264/79048522-a7256c00-7beb-11ea-8ad6-9584ce9a375b.jpg)

Able to select open the options of a creature:
![20200411115401_1](https://user-images.githubusercontent.com/37117264/79048507-7f360880-7beb-11ea-8938-20bf19560073.jpg)

**Comment by karekanol13** [comment] 2020-04-11 17:04
Same issue, stuck waiting for the adventure to begin, shadows and dice present but no models loading in

**Comment by Keksader** [comment] 2020-04-11 17:13
Found cause 

> HardAssertFailure: HandleAddLayout: layout.AssetCount     !=    _dequeuedAssetData. Lengh
999+ errors

**Comment by xRinzler** [comment] 2020-04-11 22:43
Keksader did you find a fix or just the issue?

**Comment by DariusWolfe** [comment] 2020-04-12 18:36
Same issue. For me, it may have been user error, as I'd been playing with Ctrl-X and accidentally removed my tiles. I used Ctrl-Z to restore everything before I left, but it's likely I didn't push an update before I logged out of the game. 

Video below shows the issues I'm having, including some of the same issues shown in the screenshots by ericdrejza

**Comment by cbaggers** [comment] 2020-04-15 21:55
I have a patch coming out tomorrow which takes care of the `HardAssert` issue. Once it's out I'll let you know so you can try the boards again. 

Thanks for all the info folks!

**Comment by LuPro** [comment] 2020-04-16 12:58
With the latest update, did it fix this problem for you?

**Comment by xRinzler** [comment] 2020-04-16 19:12
Update: as of 4/16/20, I am able to load and continue working on my boards since the patch to fix this. Thanks Bouncyrock!!!

**Comment by LuPro** [comment] 2020-04-21 13:39
As it has been ~5 days now and almost all issues of this kind have been resolved I'm going to close this issue, assuming the people who didn't answer also had it fixed. If this is not the case please comment here and I'll reopen the issue

**Closed by LuPro** 2020-04-21 13:39 UTC
Labels: bug, waiting on user confirmation of fix
