### ISSUE TITLE
Minis/NPC dissapear for players

### ISSUE THREAD

**Issue by SamZijnGithub** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#875] opened 2021-04-29 00:46 UTC
Placing Minis on the board as a GM works fine, but when switching to player view (and for actual players as well), the minis dissapear. To fix this, I have to set permission to me or other players for them to appear. Usually this means doing this on a couple of minis, sometimes a lot more. And mostly the ones that are further apart from each other (fixing this in area A, doesnt mean it will be fixed in area B a bit further on). The permissions dont carry on when I leave the board as well, and have to reset them each time I re-enter it.

1. Place minis on board
2. When they dissapear as a player, go back to GM and set a permission on them to either you or someone else.
3. Mostly fixes this.

Fantastic game, me and my DnD crew are spending too much time on it!

**Comment by LuPro** [comment] 2021-04-29 01:47
There is a line of sight feature that auto hides minis if they are too far away/around a corner (and thus obstructed by walls and the like). This ties into the player permissions; vision is shared in the entire "party", where "party" means "any mini that is assigned to a player" (also including the GM), so if one player's mini sees another mini, the entire party will have it revealed. As a GM you can check on the status (if a mini is visible or not) by clicking (or was it right clicking? I don't remember right now) on the mini that is "looking" and then on all other minis an eye icon should appear, small if they're not seen, big if they're seen by the selected mini. 
There have been requests by people to disable/override this automatic line of sight, but there's no concrete plans/guarantees on that front yet.

I'm closing this issue as I think this should be addressed now, if I just misinterpreted your message please do clarify and I'll reopen the issue in case there's a bug I didn't understand from your description, as it stands though it looks like this is merely the line of sight feature working as intended but maybe not communicating that well enough.

PS: The devs have said they will look into being able to split the party later on so they don't share vision if you don't want them to and some more features (fetching only one part of the players, etc)

**Closed by LuPro** 2021-04-29 01:47 UTC

**Comment by SamZijnGithub** [comment] 2021-04-29 02:01
> There is a line of sight feature that auto hides minis if they are too far away/around a corner (and thus obstructed by walls and the like). This ties into the player permissions; vision is shared in the entire "party", where "party" means "any mini that is assigned to a player" (also including the GM), so if one player's mini sees another mini, the entire party will have it revealed. As a GM you can check on the status (if a mini is visible or not) by clicking (or was it right clicking? I don't remember right now) on the mini that is "looking" and then on all other minis an eye icon should appear, small if they're not seen, big if they're seen by the selected mini.
> There have been requests by people to disable/override this automatic line of sight, but there's no concrete plans/guarantees on that front yet.
> 
> I'm closing this issue as I think this should be addressed now, if I just misinterpreted your message please do clarify and I'll reopen the issue in case there's a bug I didn't understand from your description, as it stands though it looks like this is merely the line of sight feature working as intended but maybe not communicating that well enough.
> 
> PS: The devs have said they will look into being able to split the party later on so they don't share vision if you don't want them to and some more features (fetching only one part of the players, etc)

____
Oh wow that's a neat feature! Besides this point, to make sure the roof portion of the board properly dissapears dynamically, I make a close ceiling on top of the floor. When the players enter, the roof properly dissapears (if you dont do this certain parts of the roof might show up sometimes).

So my issue here is: doing this makes certain minis dissapear when you get close to them as a playable mini. For example: the bartender in my tavern, is behind a 1x1 tiles representing a bar, moving closer to him makes him dissapear. Unless you put your Mini on top of the bar itself, which makes him appear again. So; close = appears, medium close = dissapears, further = appears. Pherhaps this is too, because of the line of sight thing?

**Comment by LuPro** [comment] 2021-04-29 02:07
Line of sight has some issues with certain tiles being in the way that block sight even if it shouldn't some of those are logged already, but yeah it's very much possible that is caused by the game thinking that the bar counter cannot be looked through at this distance/angle. That's definitely a bug, but more an issue with the asset blocking more sight than it should than with the actual line of sight system itself

**Comment by SamZijnGithub** [comment] 2021-04-29 02:09
> Line of sight has some issues with certain tiles being in the way that block sight even if it shouldn't some of those are logged already, but yeah it's very much possible that is caused by the game thinking that the bar counter cannot be looked through at this distance/angle. That's definitely a bug, but more an issue with the asset blocking more sight than it should than with the actual line of sight system itself


Thought so, I might find a work around with props or something. Thanks for the response!

**Comment by LuPro** [comment] 2021-04-29 02:12
In extreme cases assigning the mini to yourself (as the GM) can circumvent this, since vision is shared in the entire party (which includes the GM) - just keep in mind that the players will not only see the mini set to yourself, but of course also everything *that* mini sees. A lot of the issues with that line of sight stuff got "better" with the party shared Vision as it's more likely that at least *one* person is able to see it - definitely still needs to be fixed/streamlined, but it's workable for now
