### ISSUE TITLE
Managed to get a creature permanently tilted.

### ISSUE THREAD

**Issue by marcoheisig** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#43] opened 2020-04-10 21:39 UTC
**Describe the bug**
After dragging my giant rat, through some dice, it ended up some 30° tilted permanently, including the base.  No amount of dragging and teleporting could restore it to the original orientation.  I was the player in someone else's scenario.

**To Reproduce**
Couldn't reproduce immediately.  But sounds like some temporary changes to the tilt managed to permanently override the parameters of the model.  Maybe you can think of which part of the code is responsible for this.  If not, feel free to close this issue.

**Comment by marcoheisig** [comment] 2020-04-10 22:12
Oh, and here is a screenshot.  Note that the rat is not currently selected, so it should be standing on the ground.

![Rat](https://user-images.githubusercontent.com/6522938/79026254-80821980-7b88-11ea-8fe3-9926b5e1c2a3.png)

**Comment by LuPro** [comment] 2020-04-11 13:54
Similar thing also happens when a creature is being moved during an animation (like Attack), looks like those two things could be connected

**Comment by LuPro** [comment] 2020-04-12 12:45
Just went ingame and tried reproducing this, couldn't get it to work - no amount of moving a mini through dice managed to achieve this permanent tilt. The moving while an animation is displayed (like attack) does work reliably to achieve this tilt though

**Comment by marcoheisig** [comment] 2020-04-12 18:43
Moving the creature through some dice was the last thing I remember.  But we tried a lot of things in a short period of time, so maybe there was also an animation involved.

**Comment by brcoding** [comment] 2020-05-09 03:29
Vid of this happening to our group, just prior to this the group through enough dice to slow everyones games. https://www.twitch.tv/videos/615547868

**Comment by LuPro** [comment] 2021-04-17 01:12
Closing this in favor of issue #791

**Closed by LuPro** 2021-04-17 01:12 UTC
Labels: bug
