### ISSUE TITLE
moving minis using arrow keys would move the camera as well

### ISSUE THREAD

**Issue by davio-viator** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#369] opened 2020-04-15 21:14 UTC
**Describe the bug**
when you use the arrow keys to move the mini or wdsa the camera moves as well and faster than the mini so you have to manually place the camera on the mini everytime

**To Reproduce**
just move with the mini

**Comment by LuPro** [comment] 2020-04-15 23:36
Duplicate of #80

**Closed by LuPro** 2020-04-15 23:36 UTC
