### ISSUE TITLE
Tavern Wall Placement

### ISSUE THREAD

**Issue by Veska75** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#81] opened 2020-04-10 23:44 UTC
**Describe the bug**
When trying to place a number of "Tavern Wall +1 (2x1 no base)" It will place them either to the left or right of where I would like them to be placed. I have to place them one at a time to get where I want them to go.

**To Reproduce**
1. Select part
2. Hold left click and drag
3. Release left mouse button
4. OMG \0/

**Screenshots/Videos/Twitch Clips**
![SELECTING PART](https://user-images.githubusercontent.com/63480403/79029704-8dd8dd00-7b63-11ea-84fd-af0a3e974321.jpg)
![PLACING PART](https://user-images.githubusercontent.com/63480403/79029708-9204fa80-7b63-11ea-9a92-80975949ea75.jpg)
![IMPROPER PLACEMENT](https://user-images.githubusercontent.com/63480403/79029712-94ffeb00-7b63-11ea-9543-8dc47bd4dd22.jpg)

**Additional context**
Keep working hard guys!

**Comment by LuPro** [comment] 2020-04-11 21:49
Duplicate of #17, but good catch :)

**Closed by LuPro** 2020-04-11 21:49 UTC
