### ISSUE TITLE
Stacking walls works on only 2 axis

### ISSUE THREAD

**Issue by Irenicus999** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#538] opened 2020-05-13 20:17 UTC
**Describe the bug**
Placing walls using click-and-drag on second story, causes the wall to be offset by one square.
Doesnt do it on all sides only on 2 of 4

**To Reproduce**
1. create a 1st floor box room
2. attempt to stack walls on second floor (ie for cathederal)
3. click and drag wall without floor on wall above, (tired new morgoth, dungeon and tavern)
4. will apply correctly in 2 directions (ie north and east wall)
5. will not apply on remaining walls west south

**Screenshots/Videos/Twitch Clips**
![Talespire wall](https://user-images.githubusercontent.com/60137849/81860619-e9312d00-955e-11ea-9c34-7b1641d51dae.png)

**Comment by LuPro** [comment] 2020-05-14 01:39
This seems to me like a duplicate of #17 - can you confirm that this problem occurs when placing the tiles (as in, in the preview it is right, but when placing they get the offset).

**Comment by Irenicus999** [comment] 2020-05-15 18:13
The issue only occurs when trying to place multiple wall tiles at once. Placing single tiles works without issue. As per the screenshot lower left corner I am making sure that the area I am placing tiles on is exact but the tiles appear outside the selected area.

**Closed** 2021-04-13 09:40 UTC
Labels: question
