### ISSUE TITLE
Die roll result error

### ISSUE THREAD

**Issue by Velgor55** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#252] opened 2020-04-12 14:10 UTC
I was rolling a d10 and d00 for percentiles. When I rolled a 1 on the d10 and a 00 on the d00, the result displayed as 101.

**Comment by LuPro** [comment] 2020-04-12 14:28
Duplicate of issue #37

**Closed by LuPro** 2020-04-12 14:28 UTC
