### ISSUE TITLE
Build Assets filter stuck on

### ISSUE THREAD

**Issue by jamogwe** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#329] opened 2020-04-14 03:38 UTC
**Describe the bug**
Here tell us what you thought was meant to happen and then how TaleSpire vomited on itself

Couldn't remove a search filter after having left the campaign and returned to it. Build assets were stuck only showing what I had previously searched for.
![Screenshot beta bug filter](https://user-images.githubusercontent.com/45718535/79183606-e61c1300-7ddf-11ea-8d33-6432810871ff.jpg)

**To Reproduce**
1. Use filter to search for building asset
2. Leave the Campaign board to main menu
3. Return to same campaign
4. Build Assets will only show what you had previously filtered and you cannot clear the filter key word.

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by SqueeziestBee** [comment] 2020-04-14 10:10
Followed steps and was able to reproduce
![20200414110643_1](https://user-images.githubusercontent.com/47105660/79213080-79853080-7e40-11ea-8201-dc421ae1fd2b.jpg)

**Comment by Chorcon** [comment] 2020-04-14 13:20
I've noticed this too, and I've found a work-around.
Simply click the search field and hit backspace. This will remove the active search tags, one by one. :)

**Comment by jamogwe** [comment] 2020-04-14 13:24
Nice. I had to quit and go back in to the game.

**Comment by LuPro** [comment] 2020-04-14 13:56
Similar to #103, most likely the same bug internally. And as has been said, pressing backspace should remove the tags just as if you'd have entered them normally, but the representation is kinda broken

**Comment by jamogwe** [comment] 2020-04-14 14:00
Thanks, did a search but didnt see that one. Definitely the same bug, almost the exact same issue other than that I wasnt in a friends campaign. Guess you can close this one then.

**Comment by cbaggers** [comment] 2020-04-17 03:29
Thanks for the excellent work everyone.
@jamogwe, your instructions are perfect and I believe the issue is fixed in my internal build. My changes will be out in the next patch so then we can see if it works for you.

@SqueeziestBee really good catch with that exception. Not related to this bug as it happens but let me know about another one \o/. I believe that issue to also be fixed in the next patch

**Closed** 2021-05-10 14:58 UTC
Labels: bug, potentially fixed in next patch, reproducible
