### ISSUE TITLE
Bug report: Nameplates of hidden miniatures visible to players

### ISSUE THREAD

**Issue by spikeranger** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#831] opened 2021-04-20 20:41 UTC
When holding tab players are able to see nameplates of all miniatures in the game. This includes miniatures that are set as hidden by the GM

1. Create blank board, add in some grass floor tiles
2. Place single miniature (We went for cultist)
3. Set cultist to hidden
4. Have a player join the game and hold tab.

**Comment by LuPro** [comment] 2021-04-20 22:22
Duplicate of #771

**Closed by LuPro** 2021-04-20 22:22 UTC
