### ISSUE TITLE
Tile placement becomes off center when copy-pasting certain buildings

### ISSUE THREAD

**Issue by ZatchNakarie** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#460] opened 2020-04-21 14:17 UTC
**Describe the bug**
I created wall segments for a city wall that were meant to sit squarely on a 2x4 grid. But when placed next to each other in a 90 degree manor, one would become off center but half of a square. (Shown in screen shot 2). Upon testing, the slab has an invisible edge that makes it impossible to place close to other objects, forcing me to place it on top. (Screen shot 4/5)

**To Reproduce**
1. Place any building material that extends out by any square and the entire slab now shares the dimensions of that piece. 
2. Rotate or change the orientation of that piece.
3. You now have a off center slab. 
4. Removing the culprit blocks (in my case the ruined support column) fixes the issue in most cases but if removed from an already off center slab sometimes remains permanently off center. 

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

Slab in question https://talesbazaar.com/prefab/753

**Additional context**
Wonderful work so far. This was mostly an issue on my end but I'm reporting that the issue sometimes remains if blocks have already been placed. 

![1](https://user-images.githubusercontent.com/64085675/79876632-27905d80-83a0-11ea-9552-960a4801f0ad.jpg)
![2](https://user-images.githubusercontent.com/64085675/79876634-28c18a80-83a0-11ea-9a40-89ad16ce3b58.jpg)
![3](https://user-images.githubusercontent.com/64085675/79876639-28c18a80-83a0-11ea-9929-15adc15fdc75.jpg)
![4](https://user-images.githubusercontent.com/64085675/79876646-29f2b780-83a0-11ea-9033-aa518426d82c.jpg)
![5](https://user-images.githubusercontent.com/64085675/79876648-2a8b4e00-83a0-11ea-9ea5-0ee15ae9206f.jpg)
![6](https://user-images.githubusercontent.com/64085675/79876653-2a8b4e00-83a0-11ea-82b3-9bcba67a41d6.jpg)

**Comment by LuPro** [comment] 2020-04-21 14:53
Duplicate of #106, though more info is in #276

**Closed by LuPro** 2020-04-21 14:53 UTC

**Comment by cbaggers** [comment] 2020-04-21 15:32
Just adding this even though we are moving to the other issue.

With my latest fixes (which havent shipped yet) this looks like its working a bit better.
![TaleSpire - BuilderScene - PC, Mac   Linux Standalone - Unity 2019 3 0f3  PREVIEW PACKAGES IN USE  _DX11_ 2020-04-21 17 31 08](https://user-images.githubusercontent.com/1579326/79884826-fe9ab780-83f5-11ea-89cb-4d15d1fca601.png)
