### ISSUE TITLE
Dice don't appear to be very random.

### ISSUE THREAD

**Issue by palamedes** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#85] opened 2020-04-10 23:56 UTC
So in a brazen attempt to crash the game with hordes of dice (and failing.. well done).. We have noticed that there seems to be a randomness issue.

When selecting 40 d6 dice and throwing them in a small "dungeon box" I created (myself and another player did this for an hour heh) we noticed that the totals were always between 120 and 140.  

In theory, a d6 has an even chance of being a 1,2,3,4,5 or 6.  That means when you throw 40 of them, your total should be between 40 and 240.   Yet consistently our totals were between 120 and 140.  The largest we ever saw was 165, the lowest we saw was 113.   Both of these "extremes" happened only the once. 

Again, we did this for a while.  (I have no life right now... don't judge!)

This points to a possible issue.  

We ran the same test again with 6 d6 and the totals were always 17 to 27.   In theory, again, I should have seen a 6... or a 36 come up as the total.  Never came close.

Thoughts?

**Comment by Veska75** [comment] 2020-04-11 00:22
It's not a bug. It's probability. As you roll more and more dice the chance of you getting an extreme like 40 or 120 becomes nigh impossible.
The same thing happens if you roll 40d6 in real life. If you have at least 1d6 you can try it yourself.
I'll link to a probability calculator in this comment.
https://anydice.com/program/2a6c

**Comment by LuPro** [comment] 2020-04-11 22:06
As has been said, this is probability at work and luckily talespire is adhering to it :) FYI the dice in talespire are physics based, so they should be as random as any dice you can throw in real life. Closing this as it isn't a bug though

**Closed by LuPro** 2020-04-11 22:06 UTC
