### ISSUE TITLE
Cannot name board or quit the game normally.

### ISSUE THREAD

**Issue by Clickeddaisy** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#800] opened 2021-04-17 13:33 UTC
**Describe the bug**
After some time i cannot rename boards or quit the game normally via esc and pressing quit game so i have to got to task manager and end the task to quit. This has happened to me since the Chimera update.

**To Reproduce**
I am not sure what causes it but i think it might have to do with the camera mode as i like to use it to get different perspectives on the builds.

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by Clickeddaisy** [comment] 2021-04-17 13:37
I managed to find the issue after messing around a bit. If you hide the UI during camera mode then exit camera mode without unhiding the UI the bug happens.

**Comment by LuPro** [comment] 2021-04-17 20:48
Is a duplicate of #710, but that's extremely great about the recreation steps! Thanks for investigating this!

**Closed by LuPro** 2021-04-17 20:48 UTC

**Comment by cbaggers** [comment] 2021-04-21 17:04
Just wanted to say amazing work finding the steps. It made fixing this a breeze.

This will be fixed in the next patch
