### ISSUE TITLE
Goblin category in token drawer is misspelled

### ISSUE THREAD

**Issue by dails08** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#876] opened 2021-04-29 01:40 UTC
As Golbin.
![image](https://user-images.githubusercontent.com/5257309/116492497-63d78300-a86a-11eb-882d-efb8395fb717.png)

**Comment by LuPro** [comment] 2021-04-29 01:48
Duplicate of #845

**Closed by LuPro** 2021-04-29 01:48 UTC
