### ISSUE TITLE
Street lamp doesnt work

### ISSUE THREAD

**Issue by SanchotEm** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#782] opened 2021-04-16 14:35 UTC
![TS_1618583549](https://user-images.githubusercontent.com/26450544/115040418-a066be80-9efb-11eb-99df-b245b5db101a.png)

**Comment by LuPro** [comment] 2021-04-17 00:50
Duplicate of #648

**Closed by LuPro** 2021-04-17 00:50 UTC
