### ISSUE TITLE
The Dragonstatue doesnt get hidden by the hide volumes

### ISSUE THREAD

**Issue by PrezWaste** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#973] opened 2021-06-07 12:19 UTC
The Dragonstatue asset doesn't get hidden in hidevolumes!
I put the Dragonstatue into a hidden volume and the entire room when into the hide volume, but the dragon statues didnt.

**To Reproduce**
1. Place a dragonstatue on the board
2. Put the entire thing int o a hide volume
3. Watch the dragonstatue still be visible.
4. Get sad!

**Screenshots/Videos/Twitch Clips**
![Dragonstatue 1](https://user-images.githubusercontent.com/82775110/121015339-2c2df600-c79b-11eb-8c25-5272a9c5dca1.jpg)

![Dragonstatue 2](https://user-images.githubusercontent.com/82775110/121015346-30f2aa00-c79b-11eb-9dab-913f97f7d7ff.jpg)

**Additional context**
Please help, my dragons are having a mental breakdown!

**Comment by LuPro** [comment] 2021-06-13 20:20
Is it possible that the statues are sunken into the board floor a bit? hide volumes (and volume selection) has some odd behavior when interacting with object partly below the board floor

**Comment by baggers-br** [comment] 2021-12-05 12:41
Hi and thanks for the excellent report! Also good catch about the 'sunken in the floor' this @LuPro 

I've been able to replicate a couple of things

First that the sunken ones don't get hidden:
![image](https://user-images.githubusercontent.com/88878193/144746901-b4c65ed3-8e9d-4962-9f37-02ac3f0cf2ae.png)

and second that, even if they are hidden the red pattern isn't shown on the dragon statue. Weird.
![image](https://user-images.githubusercontent.com/88878193/144746888-54850bac-3b9e-4b6a-8452-2f0c53694cf2.png)

I'm going to prod around with this in the coming week to see if I can make and progress here.

**Comment by baggers-br** [comment] 2021-12-05 13:02
Ah, so the problem is that the hide-volume is (at least in some cases) not considering things in the zone below, even though they extend into the zone where the hide-volume resides. 
This shouldn't be too hard to fix, but will just take a bunch of reading to make sure we track all the cases down.

I'll try and get to this in the upcoming week. Thanks again!

**Comment by baggers-br** [comment] 2021-12-09 11:47
The fix for this has shipped. Thank you for all the help tracking this down.

**Closed by baggers-br** 2021-12-09 11:47 UTC
Labels: question, reproducible
