### ISSUE TITLE
Lamp posts have no light

### ISSUE THREAD

**Issue by Velgor55** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#847] opened 2021-04-22 17:23 UTC
Placing the double or single lamp post results in no light sources. Other light sources such as standing torches, wall torches, candles, etc. work. Reproducible on old and new boards.

**Comment by LuPro** [comment] 2021-04-22 20:41
Duplicate of #648

**Closed by LuPro** 2021-04-22 20:41 UTC
