### ISSUE TITLE
Characters are able to move during initiative

### ISSUE THREAD

**Issue by Natalia-Muray** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#886] opened 2021-05-02 16:03 UTC
**Describe the bug**
I am able to move my character about in combat when it is not my turn. 

**To Reproduce**
1. Wait for DM to start combat
2. Wait till it is not your turn
3. Use arrow keys, not WASD,

Expected:
Character is unable to act during combat unless it is their turn
Observed:
Character moves around during combat during enemy turn

**Comment by LuPro** [comment] 2021-05-03 15:35
Duplicate of/related to #102. If there's more details not mentioned there, please add those in the comments over there

**Closed by LuPro** 2021-05-03 15:35 UTC
