### ISSUE TITLE
Not being able to build when Primary mouse button is the right one.

### ISSUE THREAD

**Issue by Shadow4wolf** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#516] opened 2020-05-03 03:08 UTC
**Describe the bug**
First attempt at testing ended up going nowhere as I couldn't place objects. I tried a few things, before ultimately giving up. A while later, when I finally got back to trying it, I still was struggling placing things. As in nothing was placing. I switched the settings on my mouse from right primary mouse (I know, I'm special, I get it) to the default Left.

**To Reproduce**
Set primary button to the right button.
Try and place things down.

**Screenshots/Videos/Twitch Clips**
I don't think there's any way a picture could show anything.

**Additional context**
The game will let me cancel it just fine, but there seems to be no possible way to build without temporarily switching primary buttons

**Comment by LuPro** [comment] 2020-05-04 13:44
Duplicate of #136

**Closed by LuPro** 2020-05-04 13:44 UTC
