### ISSUE TITLE
Hide Volume no longer interactable after being edited to a 2D plane

### ISSUE THREAD

**Issue by AlbrechtWM** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#949] opened 2021-05-19 20:45 UTC
Subject says it all.  I created a hide volume, and was editing it after I created it.  I shrank it along the Z axis until it became a horizontal plane with no height.  At this point it is completely uninteractable.  I cant edit it, select it or remove it.  Please fix! =)

See attached image for illustration

![image](https://user-images.githubusercontent.com/3269909/118881966-a4527b80-b8c1-11eb-99c1-d136f2e0eb19.png)

**Comment by LuPro** [comment] 2021-05-20 13:51
Duplicate of #527

**Closed by LuPro** 2021-05-20 13:51 UTC
