### ISSUE TITLE
Can interact with structures and items on invisible floors in build mode

### ISSUE THREAD

**Issue by TrulyRudly** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#819] opened 2021-04-18 22:20 UTC
When I am building in build mode, I often start with a certain level and then add above or below that first level. Something I frequently encounter in build mode is when I am editing a floor that has another floor above it, even when I am only able to see the current floor, I am still able to grab and interact with items on the above floor that are invisible. It would surprise me if this is difficult to replicate; simply build a two story structure/multi-level dungeon starting with the top and then adding downwards, and you will inevitable select an item or structure that is invisible. If possible, locking anything that is not visible I imagine would solve this issue. Even if sometimes I don't grab the object I'm trying to select sometimes, that's a better alternative to grabbing something I delicately placed before and ruining it. Loving the game other than this issue!

**Comment by LuPro** [comment] 2021-04-18 23:02
Duplicate of #758. Though I have to say, I am unable to replicate this. Could you publish the board and comment on #758 with the board link, maybe it's something on the board that triggers this.

**Closed by LuPro** 2021-04-18 23:02 UTC
