### ISSUE TITLE
World Unit doesn´t accept decimal numbers

### ISSUE THREAD

**Issue by gamayazu** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#839] opened 2021-04-21 18:00 UTC
**Describe the bug**
Tile Size in World Units is not accepting decimal numbers. The Tile Size in my country is "1.5" of my Unity Name.

**To Reproduce**
1. Campaign and World Settings
2. World Unit
3. Try to put decimal numbers
4. Number is set to integer

**Additional context**
It would be nice if we can insert decimal numbers also

**Comment by LuPro** [comment] 2021-04-21 18:42
Duplicate of #747

**Closed by LuPro** 2021-04-21 18:42 UTC
