### ISSUE TITLE
You can flick characters into building blocks.

### ISSUE THREAD

**Issue by HatCrafter** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#38] opened 2020-04-10 21:24 UTC
**Describe the bug**
Hey, I found that when you let go of a character while flicking your mouse they'll move some extra distance. Unfortunately, if this maneuver is performed adjacent to a building block the character can be thrown into the object.

**To Reproduce**
1. Pick up the character.
2. move your mouse toward a building block at high speed.
3. Let go.
4. The character should now be inside the object.

**Screenshots/Videos/Twitch Clips**
![Capture1](https://user-images.githubusercontent.com/63477041/79024007-52301a00-7b47-11ea-95bb-9bd0c1dfdd96.PNG)
![Capture2](https://user-images.githubusercontent.com/63477041/79024010-54927400-7b47-11ea-989b-2c447fed3d48.PNG)
![Capture3](https://user-images.githubusercontent.com/63477041/79024019-578d6480-7b47-11ea-981c-e2af69e9261d.PNG)

**Additional context**
I hope this helps! I've found that you can retrieve stuck characters by moving the camera into the block that they're stuck inside.

**Comment by BlappoSpawn** [comment] 2020-04-10 21:38
I notice this only happens sometimes,   there is a small circle in center of screen, ill call it  'camera focus point' CFP   depending where it is, sometimes double clicking to select the CFP height to tile height, it can change the behavior of the mini resolving it for that individual or set of blocks.

essentially which Build Plane, BP  is the camera looking at, when selecting certain BPs it changes that behavior.

**Comment by LuPro** [comment] 2020-04-11 13:38
Some good extra info in the comments, but essentially a duplicate of #24.

**Closed by LuPro** 2020-04-11 13:38 UTC
