### ISSUE TITLE
Light source visible on board ground even when hidden.

### ISSUE THREAD

**Issue by TheKajiking** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#974] opened 2021-06-09 02:51 UTC
**Describe the bug**
I put a bunch of crystals to represent a glow coming from below a room in the sunless citadel module, however when put under a hide volume, a ring of light was left underneath on the floor of the board despite everything being hidden. 

**To Reproduce**
Put a ton of blue crystals of the larger size
put everything into a hide volume
ring appears on the floor of hide volume

**Screenshots/Videos/Twitch Clips**
![Proof of light source](https://user-images.githubusercontent.com/63574954/121284969-76de6980-c892-11eb-9a1c-15b765a31ae8.PNG)
There it is on the ground
![Proof of light source 2](https://user-images.githubusercontent.com/63574954/121285213-d63c7980-c892-11eb-9430-33b04602b7a5.PNG)
There it is on the walls of the other area.

**Additional context**
We were playing a session and i hadn't noticed it just then but my players had seen it while i was looking through the book and they didn't immidiatly go there because thankfully they can seperate OoC from IC, but i felt like i had egg on my face afterwards when they brought it up saying jokingly they should just rush to the glowing blue light.

**Comment by LuPro** [comment] 2021-06-13 20:21
Duplicate of #314

**Closed by LuPro** 2021-06-13 20:21 UTC
