### ISSUE TITLE
Keyboard controls allow movement during other's initiative

### ISSUE THREAD

**Issue by uGuardian** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#943] opened 2021-05-16 17:09 UTC
**Describe the bug**
Keyboard controls allow movement during initiative when it's not your turn.

**To Reproduce**
Use keyboard controls when it's not your turn. (Arrow keys/Shift+WASD)

**~Additional context~ Personal thoughts on the initiative system in general**
To be honest, I think you should be able to at least change your stats and make attack requests even when it's not your turn, but movement is definitely a bug and something you shouldn't.
I'd suggest a DM configuration on what actions are allowed when off-initiative.
Also it'd be nice if you could group sets of NPCs together to make the turn order cleaner.

**Comment by LuPro** [comment] 2021-05-16 18:03
Duplicate of #566
Permissions during turn based mode will be reworked (talking about the stat stuff)

**Closed by LuPro** 2021-05-16 18:03 UTC
